// Code AutoGenerated; DO NOT EDIT.

package types

// AffiliateInfo Contains information about the affiliate that received a commission via this transaction.
type AffiliateInfo struct {
	AffiliateChat      *Chat `json:"affiliate_chat,omitempty"`
	AffiliateUser      *User `json:"affiliate_user,omitempty"`
	Amount             int   `json:"amount"`
	CommissionPerMille int   `json:"commission_per_mille"`
	NanostarAmount     int   `json:"nanostar_amount,omitempty"`
}
