// Code AutoGenerated; DO NOT EDIT.

package types

// BotShortDescription Represents the bot's short description.
type BotShortDescription struct {
	ShortDescription string `json:"short_description"`
}
