// Code AutoGenerated; DO NOT EDIT.

package types

// BotSubscriptionUpdated This object contains information about changes to a user payment subscription toward the current bot.
type BotSubscriptionUpdated struct {
	InvoicePayload string `json:"invoice_payload"`
	State          string `json:"state"`
	User           User   `json:"user"`
}
