// Code AutoGenerated; DO NOT EDIT.

package types

type BusinessIntro struct {
	Message string   `json:"message,omitempty"`
	Sticker *Sticker `json:"sticker,omitempty"`
	Title   string   `json:"title,omitempty"`
}
