// Code AutoGenerated; DO NOT EDIT.

package types

type BusinessOpeningHours struct {
	OpeningHours []BusinessOpeningHoursInterval `json:"opening_hours,omitempty"`
	TimeZoneName string                         `json:"time_zone_name"`
}
