// Code AutoGenerated; DO NOT EDIT.

package types

// BusinessIntro Contains information about the start page settings of a Telegram Business account.
type BusinessIntro struct {
	Message string   `json:"message,omitempty"`
	Sticker *Sticker `json:"sticker,omitempty"`
	Title   string   `json:"title,omitempty"`
}
