// Code AutoGenerated; DO NOT EDIT.

package types

// BusinessOpeningHoursInterval Describes an interval of time during which a business is open.
type BusinessOpeningHoursInterval struct {
	ClosingMinute int `json:"closing_minute"`
	OpeningMinute int `json:"opening_minute"`
}
