// Code AutoGenerated; DO NOT EDIT.

package types

// ChatShared This object contains information about the chat whose identifier was shared with the bot using a KeyboardButtonRequestChat button.
type ChatShared struct {
	ChatID    int64 `json:"chat_id"`
	RequestID int64 `json:"request_id"`
}
