// Code AutoGenerated; DO NOT EDIT.

package types

// ChatBoostUpdated Represents a boost added to a chat or changed.
type ChatBoostUpdated struct {
	Boost ChatBoost `json:"boost"`
	Chat  Chat      `json:"chat"`
}
