// Code AutoGenerated; DO NOT EDIT.

package types

// ChatOwnerChanged Describes a service message about an ownership change in the chat.
type ChatOwnerChanged struct {
	NewOwner User `json:"new_owner"`
}
