// Code AutoGenerated; DO NOT EDIT.

package types

// ChecklistTask Describes a task in a checklist.
type ChecklistTask struct {
	CompletedByUser *User           `json:"completed_by_user,omitempty"`
	CompletionDate  int64           `json:"completion_date,omitempty"`
	ID              int64           `json:"id"`
	Text            string          `json:"text"`
	TextEntities    []MessageEntity `json:"text_entities,omitempty"`
}
