// Code AutoGenerated; DO NOT EDIT.

package types

// ChecklistTasksAdded Describes a service message about tasks added to a checklist.
type ChecklistTasksAdded struct {
	ChecklistMessage *Message        `json:"checklist_message,omitempty"`
	Tasks            []ChecklistTask `json:"tasks,omitempty"`
}
