// Code AutoGenerated; DO NOT EDIT.

package types

// CommunityChatRemoved Describes a service message about a chat being removed from a community
// Currently holds no information.
type CommunityChatRemoved any
