// Code AutoGenerated; DO NOT EDIT.

package types

// CommunityChatAdded Describes a service message about a chat being added to a community.
type CommunityChatAdded struct {
	Community Community `json:"community"`
}
