// Code AutoGenerated; DO NOT EDIT.

package types

// CopyTextButton Represents an inline keyboard button that copies specified text to the clipboard.
type CopyTextButton struct {
	Text string `json:"text"`
}
