// Code AutoGenerated; DO NOT EDIT.

package types

// DirectMessagesTopic Describes a topic of a direct messages chat.
type DirectMessagesTopic struct {
	TopicID int64 `json:"topic_id"`
	User    *User `json:"user,omitempty"`
}
