// Code AutoGenerated; DO NOT EDIT.

package types

// DirectMessagePriceChanged Describes a service message about a change in the price of direct messages sent to a channel chat.
type DirectMessagePriceChanged struct {
	AreDirectMessagesEnabled bool `json:"are_direct_messages_enabled"`
	DirectMessageStarCount   int  `json:"direct_message_star_count,omitempty"`
}
