// Code AutoGenerated; DO NOT EDIT.

package types

// EncryptedCredentials Contains data required for decrypting and authenticating EncryptedPassportElement
// See the Telegram Passport Documentation for a complete description of the data decryption and authentication processes.
type EncryptedCredentials struct {
	Data   string `json:"data"`
	Hash   string `json:"hash"`
	Secret string `json:"secret"`
}
