// Code AutoGenerated; DO NOT EDIT.

package types

// ForumTopicCreated Represents a service message about a new forum topic created in the chat.
type ForumTopicCreated struct {
	IconColor         int    `json:"icon_color"`
	IconCustomEmojiID string `json:"icon_custom_emoji_id,omitempty"`
	Name              string `json:"name"`
}
