// Code AutoGenerated; DO NOT EDIT.

package types

// ForumTopic Represents a forum topic.
type ForumTopic struct {
	IconColor         int    `json:"icon_color"`
	IconCustomEmojiID string `json:"icon_custom_emoji_id,omitempty"`
	IsNameImplicit    bool   `json:"is_name_implicit,omitempty"`
	MessageThreadID   int64  `json:"message_thread_id"`
	Name              string `json:"name"`
}
