// Code AutoGenerated; DO NOT EDIT.

package types

// ForumTopicClosed Represents a service message about a forum topic closed in the chat
// Currently holds no information.
type ForumTopicClosed any
