// Code AutoGenerated; DO NOT EDIT.

package types

// Gift Represents a gift that can be sent by the bot.
type Gift struct {
	ID             string  `json:"id"`
	RemainingCount int     `json:"remaining_count,omitempty"`
	StarCount      int     `json:"star_count"`
	Sticker        Sticker `json:"sticker"`
	TotalCount     int     `json:"total_count,omitempty"`
}
