// Code AutoGenerated; DO NOT EDIT.

package types

// GiftBackground This object describes the background of a gift.
type GiftBackground struct {
	CenterColor int `json:"center_color"`
	EdgeColor   int `json:"edge_color"`
	TextColor   int `json:"text_color"`
}
