// Code AutoGenerated; DO NOT EDIT.

package types

// GiveawayCreated Represents a service message about the creation of a scheduled giveaway
// Currently holds no information.
type GiveawayCreated any
