// Code AutoGenerated; DO NOT EDIT.

package types

// InlineKeyboardMarkup Represents an inline keyboard that appears right next to the message it belongs to.
type InlineKeyboardMarkup struct {
	InlineKeyboard [][]InlineKeyboardButton `json:"inline_keyboard,omitempty"`
}
