// Code AutoGenerated; DO NOT EDIT.

package types

import "encoding/json"

// InputRichBlockPullQuotation A quotation with centered text, loosely corresponding to the HTML tag <aside>.
type InputRichBlockPullQuotation struct {
	Credit RichTextValue `json:"credit,omitempty"`
	Text   RichTextValue `json:"text"`
	Type   string        `json:"type"`
}

func (entity *InputRichBlockPullQuotation) UnmarshalJSON(data []byte) error {
	var alias struct {
		Credit json.RawMessage `json:"credit,omitempty"`
		Text   json.RawMessage `json:"text"`
		Type   string          `json:"type"`
	}
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	var err error
	if entity.Credit, err = ParseRichTextValue(alias.Credit); err != nil {
		return err
	}
	if entity.Text, err = ParseRichTextValue(alias.Text); err != nil {
		return err
	}
	entity.Type = alias.Type
	return nil
}
