// Code AutoGenerated; DO NOT EDIT.

package types

// InputRichMessage Describes a rich message to be sent
// Exactly one of the fields html or markdown must be used.
type InputRichMessage struct {
	Html                string `json:"html,omitempty"`
	IsRtl               bool   `json:"is_rtl,omitempty"`
	Markdown            string `json:"markdown,omitempty"`
	SkipEntityDetection bool   `json:"skip_entity_detection,omitempty"`
}
