// Code AutoGenerated; DO NOT EDIT.

package types

// InputRichBlockVideo A block with a video, corresponding to the HTML tag <video>.
type InputRichBlockVideo struct {
	Caption *RichBlockCaption `json:"caption,omitempty"`
	Type    string            `json:"type"`
	Video   InputMediaVideo   `json:"video"`
}
