// Code AutoGenerated; DO NOT EDIT.

package types

// InputMessageContent Represents the content of a message to be sent as a result of an inline query
// Telegram clients currently support the following types:
//   - InputTextMessageContent
//   - InputRichMessageContent
//   - InputLocationMessageContent
//   - InputVenueMessageContent
//   - InputContactMessageContent
//   - InputInvoiceMessageContent
type InputMessageContent any
