// Code AutoGenerated; DO NOT EDIT.

package types

// InputChecklistTask Describes a task to add to a checklist.
type InputChecklistTask struct {
	ID           int64           `json:"id"`
	ParseMode    string          `json:"parse_mode,omitempty"`
	Text         string          `json:"text"`
	TextEntities []MessageEntity `json:"text_entities,omitempty"`
}
