// Code AutoGenerated; DO NOT EDIT.

package types

// InputRichBlockMap A block with a map, corresponding to the custom HTML tag <tg-map>
// The map's width and height must not exceed 10000 in total
// The width and height ratio must be at most 20.
type InputRichBlockMap struct {
	Caption  *RichBlockCaption `json:"caption,omitempty"`
	Height   int               `json:"height"`
	Location Location          `json:"location"`
	Type     string            `json:"type"`
	Width    int64             `json:"width"`
	Zoom     int               `json:"zoom"`
}
