// Code AutoGenerated; DO NOT EDIT.

package types

import rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"

// InputPaidMediaVideo The paid media to send is a video.
type InputPaidMediaVideo struct {
	Duration          int                `json:"duration,omitempty"`
	Height            int                `json:"height,omitempty"`
	Media             rawTypes.InputFile `json:"media,omitempty"`
	SupportsStreaming bool               `json:"supports_streaming,omitempty"`
	Thumbnail         rawTypes.InputFile `json:"thumbnail,omitempty"`
	Type              string             `json:"type"`
	Width             int64              `json:"width,omitempty"`
}
