// Code AutoGenerated; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// InputPaidMediaLivePhoto The paid media to send is a live photo.
type InputPaidMediaLivePhoto struct {
	Media rawTypes.InputFile `json:"media,omitempty"`
	Photo string             `json:"photo"`
}

func (entity *InputPaidMediaLivePhoto) Files() map[string]rawTypes.InputFile {
	files := make(map[string]rawTypes.InputFile)
	switch entity.Media.(type) {
	case InputBytes:
		files["livephoto"] = entity.Media
	}
	return files
}

func (entity *InputPaidMediaLivePhoto) SetAttachment(attach string) {
	entity.Media = InputURL(fmt.Sprintf("attach://%s", attach))
}

func (entity *InputPaidMediaLivePhoto) SetAttachmentThumb(_ string) {
}

func (entity InputPaidMediaLivePhoto) MarshalJSON() ([]byte, error) {
	alias := struct {
		Type  string             `json:"type"`
		Media rawTypes.InputFile `json:"media,omitempty"`
		Photo string             `json:"photo"`
	}{
		Type:  "live_photo",
		Media: entity.Media,
		Photo: entity.Photo,
	}
	return json.Marshal(alias)
}
