// Code AutoGenerated; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// InputRichBlockCollage A collage, corresponding to the custom HTML tag <tg-collage>.
type InputRichBlockCollage struct {
	Blocks  []InputRichBlock  `json:"blocks,omitempty"`
	Caption *RichBlockCaption `json:"caption,omitempty"`
	Type    string            `json:"type"`
}

func (entity InputRichBlockCollage) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if nilCheck(entity.Caption) {
		entity.Caption = nil
	}
	for _, x0 := range entity.Blocks {
		switch x0.(type) {
		case InputRichBlockParagraph, InputRichBlockSectionHeading, InputRichBlockPreformatted, InputRichBlockFooter, InputRichBlockDivider, InputRichBlockMathematicalExpression, InputRichBlockAnchor, InputRichBlockList, InputRichBlockBlockQuotation, InputRichBlockPullQuotation, InputRichBlockCollage, InputRichBlockSlideshow, InputRichBlockTable, InputRichBlockDetails, InputRichBlockMap, InputRichBlockAnimation, InputRichBlockAudio, InputRichBlockPhoto, InputRichBlockVideo, InputRichBlockVoiceNote, InputRichBlockThinking:
			break
		default:
			return nil, fmt.Errorf("blocks: unknown type: %T", x0)
		}
	}
	type x0 InputRichBlockCollage
	return json.Marshal((x0)(entity))
}
