// Code AutoGenerated; DO NOT EDIT.

package types

import "encoding/json"

// InputRichBlockThinking A block with a “Thinking…” placeholder, corresponding to the custom HTML tag <tg-thinking>
// The block may be used only in sendRichMessageDraft, therefore it can't be received in messages
// See https://t.me/addemoji/AIActions for examples of custom emoji that are recommended for usage in the block.
type InputRichBlockThinking struct {
	Text RichTextValue `json:"text"`
	Type string        `json:"type"`
}

func (entity *InputRichBlockThinking) UnmarshalJSON(data []byte) error {
	var alias struct {
		Text json.RawMessage `json:"text"`
		Type string          `json:"type"`
	}
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	var err error
	if entity.Text, err = ParseRichTextValue(alias.Text); err != nil {
		return err
	}
	entity.Type = alias.Type
	return nil
}
