// Code AutoGenerated; DO NOT EDIT.

package types

// InputProfilePhoto This object describes a profile photo to set
// Currently, it can be one of
//   - InputProfilePhotoStatic
//   - InputProfilePhotoAnimated
type InputProfilePhoto any
