// Code AutoGenerated; DO NOT EDIT.

package types

import "encoding/json"

// InputStoryContentPhoto Describes a photo to post as a story.
type InputStoryContentPhoto struct {
	Photo string `json:"photo"`
}

func (entity InputStoryContentPhoto) MarshalJSON() ([]byte, error) {
	alias := struct {
		Type  string `json:"type"`
		Photo string `json:"photo"`
	}{
		Type:  "photo",
		Photo: entity.Photo,
	}
	return json.Marshal(alias)
}
