// Code AutoGenerated; DO NOT EDIT.

package types

// InputPollOptionMedia Represents the content of a poll option to be sent
// It should be one of
//   - InputMediaAnimation
//   - InputMediaLivePhoto
//   - InputMediaLocation
//   - InputMediaPhoto
//   - InputMediaSticker
//   - InputMediaVenue
//   - InputMediaVideo
type InputPollOptionMedia interface {
	SetAttachment(string)
	SetAttachmentThumb(string)
}
