// Code AutoGenerated; DO NOT EDIT.

package types

import (
	"encoding/json"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// InputMediaLink Represents an HTTP link to be sent.
type InputMediaLink struct {
	URL string `json:"url"`
}

func (entity *InputMediaLink) Files() map[string]rawTypes.InputFile {
	files := make(map[string]rawTypes.InputFile)
	return files
}

func (entity *InputMediaLink) SetAttachment(_ string) {
}

func (entity *InputMediaLink) SetAttachmentThumb(_ string) {
}

func (entity InputMediaLink) MarshalJSON() ([]byte, error) {
	alias := struct {
		Type string `json:"type"`
		URL  string `json:"url"`
	}{
		Type: "link",
		URL:  entity.URL,
	}
	return json.Marshal(alias)
}
