// Code AutoGenerated; DO NOT EDIT.

package types

import (
	"encoding/json"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// InputMediaLocation Represents a location to be sent.
type InputMediaLocation struct {
	HorizontalAccuracy float64 `json:"horizontal_accuracy,omitempty"`
	Latitude           float64 `json:"latitude"`
	Longitude          float64 `json:"longitude"`
}

func (entity *InputMediaLocation) Files() map[string]rawTypes.InputFile {
	files := make(map[string]rawTypes.InputFile)
	return files
}

func (entity *InputMediaLocation) SetAttachment(_ string) {
}

func (entity *InputMediaLocation) SetAttachmentThumb(_ string) {
}

func (entity InputMediaLocation) MarshalJSON() ([]byte, error) {
	alias := struct {
		Type               string  `json:"type"`
		Latitude           float64 `json:"latitude"`
		Longitude          float64 `json:"longitude"`
		HorizontalAccuracy float64 `json:"horizontal_accuracy,omitempty"`
	}{
		Type:               "location",
		Latitude:           entity.Latitude,
		Longitude:          entity.Longitude,
		HorizontalAccuracy: entity.HorizontalAccuracy,
	}
	return json.Marshal(alias)
}
