// Code AutoGenerated; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// InputMediaVenue Represents a venue to be sent.
type InputMediaVenue struct {
	Address         string  `json:"address"`
	FoursquareID    string  `json:"foursquare_id,omitempty"`
	FoursquareType  string  `json:"foursquare_type,omitempty"`
	GooglePlaceID   string  `json:"google_place_id,omitempty"`
	GooglePlaceType string  `json:"google_place_type,omitempty"`
	Latitude        float64 `json:"latitude"`
	Longitude       float64 `json:"longitude"`
	Title           string  `json:"title"`
}

func (entity *InputMediaVenue) Files() map[string]rawTypes.InputFile {
	files := make(map[string]rawTypes.InputFile)
	return files
}

func (entity *InputMediaVenue) SetAttachment(attach string) {
	entity.Media = InputURL(fmt.Sprintf("attach://%s", attach))
}

func (entity *InputMediaVenue) SetAttachmentThumb(_ string) {
}

func (entity InputMediaVenue) MarshalJSON() ([]byte, error) {
	alias := struct {
		Type            string  `json:"type"`
		Latitude        float64 `json:"latitude"`
		Longitude       float64 `json:"longitude"`
		Title           string  `json:"title"`
		Address         string  `json:"address"`
		FoursquareID    string  `json:"foursquare_id,omitempty"`
		FoursquareType  string  `json:"foursquare_type,omitempty"`
		GooglePlaceID   string  `json:"google_place_id,omitempty"`
		GooglePlaceType string  `json:"google_place_type,omitempty"`
	}{
		Type:            "venue",
		Latitude:        entity.Latitude,
		Longitude:       entity.Longitude,
		Title:           entity.Title,
		Address:         entity.Address,
		FoursquareID:    entity.FoursquareID,
		FoursquareType:  entity.FoursquareType,
		GooglePlaceID:   entity.GooglePlaceID,
		GooglePlaceType: entity.GooglePlaceType,
	}
	return json.Marshal(alias)
}
