// Code AutoGenerated; DO NOT EDIT.

package types

import "encoding/json"

// InputRichBlockParagraph A text paragraph, corresponding to the HTML tag <p>.
type InputRichBlockParagraph struct {
	Text RichTextValue `json:"text"`
	Type string        `json:"type"`
}

func (entity *InputRichBlockParagraph) UnmarshalJSON(data []byte) error {
	var alias struct {
		Text json.RawMessage `json:"text"`
		Type string          `json:"type"`
	}
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	var err error
	if entity.Text, err = ParseRichTextValue(alias.Text); err != nil {
		return err
	}
	entity.Type = alias.Type
	return nil
}
