// Code AutoGenerated; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// InputMediaSticker Represents a sticker file to be sent.
type InputMediaSticker struct {
	Emoji string             `json:"emoji,omitempty"`
	Media rawTypes.InputFile `json:"media,omitempty"`
}

func (entity *InputMediaSticker) Files() map[string]rawTypes.InputFile {
	files := make(map[string]rawTypes.InputFile)
	switch entity.Media.(type) {
	case InputBytes:
		files["sticker"] = entity.Media
	}
	return files
}

func (entity *InputMediaSticker) SetAttachment(attach string) {
	entity.Media = InputURL(fmt.Sprintf("attach://%s", attach))
}

func (entity *InputMediaSticker) SetAttachmentThumb(_ string) {
}

func (entity InputMediaSticker) MarshalJSON() ([]byte, error) {
	alias := struct {
		Type  string             `json:"type"`
		Media rawTypes.InputFile `json:"media,omitempty"`
		Emoji string             `json:"emoji,omitempty"`
	}{
		Type:  "sticker",
		Media: entity.Media,
		Emoji: entity.Emoji,
	}
	return json.Marshal(alias)
}
