// Code AutoGenerated; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// InputRichBlockDetails An expandable block for details disclosure, corresponding to the HTML tag <details>.
type InputRichBlockDetails struct {
	Blocks  []InputRichBlock `json:"blocks,omitempty"`
	IsOpen  bool             `json:"is_open,omitempty"`
	Summary RichTextValue    `json:"summary"`
	Type    string           `json:"type"`
}

func (entity *InputRichBlockDetails) UnmarshalJSON(data []byte) error {
	var alias struct {
		Blocks  []InputRichBlock `json:"blocks,omitempty"`
		IsOpen  bool             `json:"is_open,omitempty"`
		Summary json.RawMessage  `json:"summary"`
		Type    string           `json:"type"`
	}
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	var err error
	entity.Blocks = alias.Blocks
	entity.IsOpen = alias.IsOpen
	if entity.Summary, err = ParseRichTextValue(alias.Summary); err != nil {
		return err
	}
	entity.Type = alias.Type
	return nil
}

func (entity InputRichBlockDetails) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	for _, x0 := range entity.Blocks {
		switch x0.(type) {
		case InputRichBlockParagraph, InputRichBlockSectionHeading, InputRichBlockPreformatted, InputRichBlockFooter, InputRichBlockDivider, InputRichBlockMathematicalExpression, InputRichBlockAnchor, InputRichBlockList, InputRichBlockBlockQuotation, InputRichBlockPullQuotation, InputRichBlockCollage, InputRichBlockSlideshow, InputRichBlockTable, InputRichBlockDetails, InputRichBlockMap, InputRichBlockAnimation, InputRichBlockAudio, InputRichBlockPhoto, InputRichBlockVideo, InputRichBlockVoiceNote, InputRichBlockThinking:
			break
		default:
			return nil, fmt.Errorf("blocks: unknown type: %T", x0)
		}
	}
	type x0 InputRichBlockDetails
	return json.Marshal((x0)(entity))
}
