// Code AutoGenerated; DO NOT EDIT.

package types

// InputRichBlockPhoto A block with a photo, corresponding to the HTML tag <img>.
type InputRichBlockPhoto struct {
	Caption *RichBlockCaption `json:"caption,omitempty"`
	Photo   InputMediaPhoto   `json:"photo"`
	Type    string            `json:"type"`
}
