// Code AutoGenerated; DO NOT EDIT.

package types

// InputProfilePhotoStatic A static profile photo in the .JPG format.
type InputProfilePhotoStatic struct {
	Photo string `json:"photo"`
	Type  string `json:"type"`
}
