// Code AutoGenerated; DO NOT EDIT.

package types

// InputPollMedia Represents the content of a poll description or a quiz explanation to be sent
// It should be one of
//   - InputMediaAnimation
//   - InputMediaAudio
//   - InputMediaDocument
//   - InputMediaLivePhoto
//   - InputMediaLocation
//   - InputMediaPhoto
//   - InputMediaVenue
//   - InputMediaVideo
type InputPollMedia interface {
	SetAttachment(string)
	SetAttachmentThumb(string)
}
