// Code AutoGenerated; DO NOT EDIT.

package types

import "encoding/json"

// InputRichBlockPreformatted A preformatted text block, corresponding to the nested HTML tags <pre> and <code>.
type InputRichBlockPreformatted struct {
	Language string        `json:"language,omitempty"`
	Text     RichTextValue `json:"text"`
	Type     string        `json:"type"`
}

func (entity *InputRichBlockPreformatted) UnmarshalJSON(data []byte) error {
	var alias struct {
		Language string          `json:"language,omitempty"`
		Text     json.RawMessage `json:"text"`
		Type     string          `json:"type"`
	}
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	var err error
	entity.Language = alias.Language
	if entity.Text, err = ParseRichTextValue(alias.Text); err != nil {
		return err
	}
	entity.Type = alias.Type
	return nil
}
