// Code AutoGenerated; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// InputMediaLivePhoto Represents a live photo to be sent.
type InputMediaLivePhoto struct {
	Caption               string             `json:"caption,omitempty"`
	CaptionEntities       []MessageEntity    `json:"caption_entities,omitempty"`
	HasSpoiler            bool               `json:"has_spoiler,omitempty"`
	Media                 rawTypes.InputFile `json:"media,omitempty"`
	ParseMode             string             `json:"parse_mode,omitempty"`
	Photo                 string             `json:"photo"`
	ShowCaptionAboveMedia bool               `json:"show_caption_above_media,omitempty"`
}

func (entity *InputMediaLivePhoto) Files() map[string]rawTypes.InputFile {
	files := make(map[string]rawTypes.InputFile)
	switch entity.Media.(type) {
	case InputBytes:
		files["livephoto"] = entity.Media
	}
	return files
}

func (entity *InputMediaLivePhoto) SetAttachment(attach string) {
	entity.Media = InputURL(fmt.Sprintf("attach://%s", attach))
}

func (entity *InputMediaLivePhoto) SetAttachmentThumb(_ string) {
}

func (entity InputMediaLivePhoto) MarshalJSON() ([]byte, error) {
	alias := struct {
		Type                  string             `json:"type"`
		Media                 rawTypes.InputFile `json:"media,omitempty"`
		Photo                 string             `json:"photo"`
		Caption               string             `json:"caption,omitempty"`
		ParseMode             string             `json:"parse_mode,omitempty"`
		CaptionEntities       []MessageEntity    `json:"caption_entities,omitempty"`
		ShowCaptionAboveMedia bool               `json:"show_caption_above_media,omitempty"`
		HasSpoiler            bool               `json:"has_spoiler,omitempty"`
	}{
		Type:                  "live_photo",
		Media:                 entity.Media,
		Photo:                 entity.Photo,
		Caption:               entity.Caption,
		ParseMode:             entity.ParseMode,
		CaptionEntities:       entity.CaptionEntities,
		ShowCaptionAboveMedia: entity.ShowCaptionAboveMedia,
		HasSpoiler:            entity.HasSpoiler,
	}
	return json.Marshal(alias)
}
