// Code AutoGenerated; DO NOT EDIT.

package types

// KeyboardButtonRequestManagedBot This object defines the parameters for the creation of a managed bot
// Information about the created bot will be shared with the bot using the update managed_bot and a Message with the field managed_bot_created.
type KeyboardButtonRequestManagedBot struct {
	RequestID         int64  `json:"request_id"`
	SuggestedName     string `json:"suggested_name,omitempty"`
	SuggestedUsername string `json:"suggested_username,omitempty"`
}
