// Code AutoGenerated; DO NOT EDIT.

package types

// KeyboardButtonRequestChat This object defines the criteria used to request a suitable chat
// The identifier of the selected chat will be shared with the bot when the corresponding button is pressed
// More about requesting chats »
type KeyboardButtonRequestChat struct {
	BotAdministratorRights  *ChatAdministratorRights `json:"bot_administrator_rights,omitempty"`
	BotIsMember             bool                     `json:"bot_is_member,omitempty"`
	ChatHasUsername         bool                     `json:"chat_has_username,omitempty"`
	ChatIsChannel           bool                     `json:"chat_is_channel"`
	ChatIsCreated           bool                     `json:"chat_is_created,omitempty"`
	ChatIsForum             bool                     `json:"chat_is_forum,omitempty"`
	RequestID               int64                    `json:"request_id"`
	UserAdministratorRights *ChatAdministratorRights `json:"user_administrator_rights,omitempty"`
}
