// Code AutoGenerated; DO NOT EDIT.

package types

// BACKGROUND_FILL
const (
	TypeBackgroundFillSolid = iota
	TypeBackgroundFillGradient
	TypeBackgroundFillFreeformGradient
)

// BACKGROUND_TYPE
const (
	TypeBackgroundTypeFill = iota
	TypeBackgroundTypeWallpaper
	TypeBackgroundTypePattern
	TypeBackgroundTypeChatTheme
)

// CHAT_BOOST_SOURCE
const (
	TypeChatBoostSourcePremium = iota
	TypeChatBoostSourceGiftCode
	TypeChatBoostSourceGiveaway
)

// CHAT_MEMBER
const (
	TypeChatMemberOwner = iota
	TypeChatMemberAdministrator
	TypeChatMemberMember
	TypeChatMemberRestricted
	TypeChatMemberLeft
	TypeChatMemberBanned
)

// MAYBE_INACCESSIBLE_MESSAGE
const (
	TypeMessage = iota
	TypeInaccessibleMessage
)

// MESSAGE_ORIGIN
const (
	TypeMessageOriginUser = iota
	TypeMessageOriginHiddenUser
	TypeMessageOriginChat
	TypeMessageOriginChannel
)

// OWNED_GIFT
const (
	TypeOwnedGiftRegular = iota
	TypeOwnedGiftUnique
)

// PAID_MEDIA
const (
	TypePaidMediaLivePhoto = iota
	TypePaidMediaPhoto
	TypePaidMediaPreview
	TypePaidMediaVideo
)

// REVENUE_WITHDRAWAL_STATE
const (
	TypeRevenueWithdrawalStatePending = iota
	TypeRevenueWithdrawalStateSucceeded
	TypeRevenueWithdrawalStateFailed
)

// RICH_BLOCK
const (
	TypeRichBlockParagraph = iota
	TypeRichBlockSectionHeading
	TypeRichBlockPreformatted
	TypeRichBlockFooter
	TypeRichBlockDivider
	TypeRichBlockMathematicalExpression
	TypeRichBlockAnchor
	TypeRichBlockList
	TypeRichBlockBlockQuotation
	TypeRichBlockPullQuotation
	TypeRichBlockCollage
	TypeRichBlockSlideshow
	TypeRichBlockTable
	TypeRichBlockDetails
	TypeRichBlockMap
	TypeRichBlockAnimation
	TypeRichBlockAudio
	TypeRichBlockPhoto
	TypeRichBlockVideo
	TypeRichBlockVoiceNote
	TypeRichBlockThinking
)

// RICH_TEXT
const (
	TypeRichTextBold = iota
	TypeRichTextItalic
	TypeRichTextUnderline
	TypeRichTextStrikethrough
	TypeRichTextSpoiler
	TypeRichTextDateTime
	TypeRichTextTextMention
	TypeRichTextSubscript
	TypeRichTextSuperscript
	TypeRichTextMarked
	TypeRichTextCode
	TypeRichTextCustomEmoji
	TypeRichTextMathematicalExpression
	TypeRichTextUrl
	TypeRichTextEmailAddress
	TypeRichTextPhoneNumber
	TypeRichTextBankCardNumber
	TypeRichTextMention
	TypeRichTextHashtag
	TypeRichTextCashtag
	TypeRichTextBotCommand
	TypeRichTextAnchor
	TypeRichTextAnchorLink
	TypeRichTextReference
	TypeRichTextReferenceLink
	TypeRichTextPlain
	TypeRichTextArray
)

// STORY_AREA_TYPE
const (
	TypeStoryAreaTypeLocation = iota
	TypeStoryAreaTypeSuggestedReaction
	TypeStoryAreaTypeLink
	TypeStoryAreaTypeWeather
	TypeStoryAreaTypeUniqueGift
)

// TRANSACTION_PARTNER
const (
	TypeTransactionPartnerUser = iota
	TypeTransactionPartnerChat
	TypeTransactionPartnerAffiliateProgram
	TypeTransactionPartnerFragment
	TypeTransactionPartnerTelegramAds
	TypeTransactionPartnerTelegramApi
	TypeTransactionPartnerOther
)

// RETURN_TYPES
const (
	TypeArrayOfBotCommand = iota
	TypeArrayOfChatMember
	TypeArrayOfGameHighScore
	TypeArrayOfMessage
	TypeArrayOfMessageId
	TypeArrayOfSticker
	TypeArrayOfUpdate
	TypeBoolean
	TypeBotAccessSettings
	TypeBotDescription
	TypeBotName
	TypeBotShortDescription
	TypeBusinessConnection
	TypeChatAdministratorRights
	TypeChatFullInfo
	TypeChatInviteLink
	TypeChatMember
	TypeErrorMessage
	TypeFile
	TypeForumTopic
	TypeGifts
	TypeInteger
	TypeMenuButton
	TypeMessageId
	TypeOwnedGifts
	TypePoll
	TypePreparedInlineMessage
	TypePreparedKeyboardButton
	TypeSentGuestMessage
	TypeSentWebAppMessage
	TypeStarAmount
	TypeStarTransactions
	TypeStickerSet
	TypeStory
	TypeString
	TypeUser
	TypeUserChatBoosts
	TypeUserProfileAudios
	TypeUserProfilePhotos
	TypeWebhookInfo
)
