// Code AutoGenerated; DO NOT EDIT.

package types

// MAYBE_INACCESSIBLE_MESSAGE
const (
	TypeMessage = iota
	TypeInaccessibleMessage
)

// CHAT_BOOST_SOURCE
const (
	TypeChatBoostSourcePremium = iota
	TypeChatBoostSourceGiftCode
	TypeChatBoostSourceGiveaway
)

// CHAT_MEMBER
const (
	TypeChatMemberOwner = iota
	TypeChatMemberAdministrator
	TypeChatMemberMember
	TypeChatMemberRestricted
	TypeChatMemberLeft
	TypeChatMemberBanned
)

// MESSAGE_ORIGIN
const (
	TypeMessageOriginUser = iota
	TypeMessageOriginHiddenUser
	TypeMessageOriginChat
	TypeMessageOriginChannel
)

// RETURN_TYPES
const (
	TypeArrayOfBotCommand = iota
	TypeArrayOfChatMember
	TypeArrayOfGameHighScore
	TypeArrayOfMessage
	TypeArrayOfMessageId
	TypeArrayOfSticker
	TypeArrayOfUpdate
	TypeBoolean
	TypeBotDescription
	TypeBotName
	TypeBotShortDescription
	TypeBusinessConnection
	TypeChat
	TypeChatAdministratorRights
	TypeChatInviteLink
	TypeChatMember
	TypeErrorMessage
	TypeFile
	TypeForumTopic
	TypeInteger
	TypeMenuButton
	TypeMessageId
	TypePoll
	TypeSentWebAppMessage
	TypeStickerSet
	TypeString
	TypeUser
	TypeUserChatBoosts
	TypeUserProfilePhotos
	TypeWebhookInfo
)
