// Code AutoGenerated; DO NOT EDIT.

package types

// LinkPreviewOptions Describes the options used for link preview generation.
type LinkPreviewOptions struct {
	IsDisabled       bool   `json:"is_disabled,omitempty"`
	PreferLargeMedia bool   `json:"prefer_large_media,omitempty"`
	PreferSmallMedia bool   `json:"prefer_small_media,omitempty"`
	ShowAboveText    bool   `json:"show_above_text,omitempty"`
	URL              string `json:"url,omitempty"`
}
