// Code AutoGenerated; DO NOT EDIT.

package types

// LocationAddress Describes the physical address of a location.
type LocationAddress struct {
	City        string `json:"city,omitempty"`
	CountryCode string `json:"country_code"`
	State       string `json:"state,omitempty"`
	Street      string `json:"street,omitempty"`
}
