// Code AutoGenerated; DO NOT EDIT.

package types

// ManagedBotUpdated This object contains information about the creation or token update of a bot that is managed by the current bot.
type ManagedBotUpdated struct {
	Bot  User `json:"bot"`
	User User `json:"user"`
}
