// Code AutoGenerated; DO NOT EDIT.

package types

import "encoding/json"

// MenuButtonCommands Represents a menu button, which opens the bot's list of commands.
type MenuButtonCommands struct {
}

func (entity MenuButtonCommands) MarshalJSON() ([]byte, error) {
	alias := struct {
		Type string `json:"type"`
	}{
		Type: "commands",
	}
	return json.Marshal(alias)
}
