// Code AutoGenerated; DO NOT EDIT.

package types

// MessageEntity Represents one special entity in a text message
// For example, hashtags, usernames, URLs, etc.
type MessageEntity struct {
	CustomEmojiID string `json:"custom_emoji_id,omitempty"`
	Language      string `json:"language,omitempty"`
	Length        int    `json:"length"`
	Offset        int    `json:"offset"`
	Type          string `json:"type"`
	URL           string `json:"url,omitempty"`
	User          *User  `json:"user,omitempty"`
}
