// Code AutoGenerated; DO NOT EDIT.

package types

// OwnedGifts Contains the list of gifts received and owned by a user or a chat.
type OwnedGifts struct {
	Gifts      []OwnedGift `json:"gifts,omitempty"`
	NextOffset string      `json:"next_offset,omitempty"`
	TotalCount int         `json:"total_count"`
}
