// Code AutoGenerated; DO NOT EDIT.

package types

// OwnedGift This object describes a gift received and owned by a user or a chat
// Currently, it can be one of
//   - OwnedGiftRegular
//   - OwnedGiftUnique
type OwnedGift struct {
	CanBeTransferred        bool            `json:"can_be_transferred"`
	CanBeUpgraded           bool            `json:"can_be_upgraded"`
	ConvertStarCount        int             `json:"convert_star_count"`
	Entities                []MessageEntity `json:"entities"`
	Gift                    Gift            `json:"gift"`
	IsPrivate               bool            `json:"is_private"`
	IsSaved                 bool            `json:"is_saved"`
	OwnedGiftID             string          `json:"owned_gift_id"`
	PrepaidUpgradeStarCount int64           `json:"prepaid_upgrade_star_count"`
	SendDate                int64           `json:"send_date"`
	SenderUser              *User           `json:"sender_user"`
	Text                    string          `json:"text"`
	TransferStarCount       int             `json:"transfer_star_count"`
	Type                    string          `json:"type"`
	WasRefunded             bool            `json:"was_refunded"`
}

func (x OwnedGift) Kind() int {
	switch x.Type {
	case "regular":
		return TypeOwnedGiftRegular
	case "unique":
		return TypeOwnedGiftUnique
	default:
		return -1
	}
}
