// Code AutoGenerated; DO NOT EDIT.

package types

// PaidMediaPurchased This object contains information about a paid media purchase.
type PaidMediaPurchased struct {
	From             User   `json:"from"`
	PaidMediaPayload string `json:"paid_media_payload"`
}
