// Code AutoGenerated; DO NOT EDIT.

package types

// PaidMedia This object describes paid media
// Currently, it can be one of
//  - PaidMediaPreview
//  - PaidMediaPhoto
//  - PaidMediaVideo
type PaidMedia struct {
	Duration int         `json:"duration"`
	Height   int         `json:"height"`
	Photo    []PhotoSize `json:"photo"`
	Type     string      `json:"type"`
	Video    Video       `json:"video"`
	Width    int64       `json:"width"`
}

func (x PaidMedia) Kind() int {
	switch x.Type {
	case "preview":
		return TypePaidMediaPreview
	case "photo":
		return TypePaidMediaPhoto
	case "video":
		return TypePaidMediaVideo
	default:
		return -1
	}
}
