// Code AutoGenerated; DO NOT EDIT.

package types

// PollOption This object contains information about one answer option in a poll.
type PollOption struct {
	Text         string          `json:"text"`
	TextEntities []MessageEntity `json:"text_entities,omitempty"`
	VoterCount   int             `json:"voter_count"`
}
