// Code AutoGenerated; DO NOT EDIT.

package types

// PollOption This object contains information about one answer option in a poll.
type PollOption struct {
	Text string `json:"text"`
	VoterCount int `json:"voter_count"`
}
