// Code AutoGenerated; DO NOT EDIT.

package types

// PollOptionDeleted Describes a service message about an option deleted from a poll.
type PollOptionDeleted struct {
	OptionPersistentID string                    `json:"option_persistent_id"`
	OptionText         string                    `json:"option_text"`
	OptionTextEntities []MessageEntity           `json:"option_text_entities,omitempty"`
	PollMessage        *MaybeInaccessibleMessage `json:"poll_message,omitempty"`
}
