// Code AutoGenerated; DO NOT EDIT.

package types

// Poll This object contains information about a poll.
type Poll struct {
	AllowsMultipleAnswers bool            `json:"allows_multiple_answers"`
	AllowsRevoting        bool            `json:"allows_revoting"`
	CloseDate             int64           `json:"close_date,omitempty"`
	CorrectOptionIDs      []int64         `json:"correct_option_ids,omitempty"`
	Description           string          `json:"description,omitempty"`
	DescriptionEntities   []MessageEntity `json:"description_entities,omitempty"`
	Explanation           string          `json:"explanation,omitempty"`
	ExplanationEntities   []MessageEntity `json:"explanation_entities,omitempty"`
	ID                    string          `json:"id"`
	IsAnonymous           bool            `json:"is_anonymous"`
	IsClosed              bool            `json:"is_closed"`
	OpenPeriod            int             `json:"open_period,omitempty"`
	Options               []PollOption    `json:"options,omitempty"`
	Question              string          `json:"question"`
	QuestionEntities      []MessageEntity `json:"question_entities,omitempty"`
	TotalVoterCount       int             `json:"total_voter_count"`
	Type                  string          `json:"type"`
}
