// Code AutoGenerated; DO NOT EDIT.

package types

// PollOptionAdded Describes a service message about an option added to a poll.
type PollOptionAdded struct {
	OptionPersistentID string                    `json:"option_persistent_id"`
	OptionText         string                    `json:"option_text"`
	OptionTextEntities []MessageEntity           `json:"option_text_entities,omitempty"`
	PollMessage        *MaybeInaccessibleMessage `json:"poll_message,omitempty"`
}
