// Code AutoGenerated; DO NOT EDIT.

package types

// PreparedKeyboardButton Describes a keyboard button to be used by a user of a Mini App.
type PreparedKeyboardButton struct {
	ID string `json:"id"`
}
