// Code AutoGenerated; DO NOT EDIT.

package types

// ReactionType This object describes the type of a reaction
// Currently, it can be one of
//  - ReactionTypeEmoji
//  - ReactionTypeCustomEmoji
//  - ReactionTypePaid
type ReactionType any
