// Code AutoGenerated; DO NOT EDIT.

package types

// RefundedPayment This object contains basic information about a refunded payment.
type RefundedPayment struct {
	Currency                string `json:"currency"`
	InvoicePayload          string `json:"invoice_payload"`
	ProviderPaymentChargeID string `json:"provider_payment_charge_id,omitempty"`
	TelegramPaymentChargeID string `json:"telegram_payment_charge_id"`
	TotalAmount             int    `json:"total_amount"`
}
