// Code AutoGenerated; DO NOT EDIT.

package types

// ResponseParameters Describes why a request was unsuccessful.
type ResponseParameters struct {
	MigrateToChatID int64 `json:"migrate_to_chat_id,omitempty"`
	RetryAfter      int   `json:"retry_after,omitempty"`
}
