// Code AutoGenerated; DO NOT EDIT.

package types

// RichBlock Represents a block in a rich formatted message
// Currently, it can be any of the following types:
//   - RichBlockParagraph
//   - RichBlockSectionHeading
//   - RichBlockPreformatted
//   - RichBlockFooter
//   - RichBlockDivider
//   - RichBlockMathematicalExpression
//   - RichBlockAnchor
//   - RichBlockList
//   - RichBlockBlockQuotation
//   - RichBlockPullQuotation
//   - RichBlockCollage
//   - RichBlockSlideshow
//   - RichBlockTable
//   - RichBlockDetails
//   - RichBlockMap
//   - RichBlockAnimation
//   - RichBlockAudio
//   - RichBlockPhoto
//   - RichBlockVideo
//   - RichBlockVoiceNote
//   - RichBlockThinking
type RichBlock struct {
	Animation  Animation              `json:"animation"`
	Audio      Audio                  `json:"audio"`
	Blocks     []RichBlock            `json:"blocks"`
	Caption    *RichBlockCaption      `json:"caption"`
	Cells      [][]RichBlockTableCell `json:"cells"`
	Credit     *RichText              `json:"credit"`
	Expression string                 `json:"expression"`
	HasSpoiler bool                   `json:"has_spoiler"`
	Height     int                    `json:"height"`
	IsBordered bool                   `json:"is_bordered"`
	IsOpen     bool                   `json:"is_open"`
	IsStriped  bool                   `json:"is_striped"`
	Items      []RichBlockListItem    `json:"items"`
	Language   string                 `json:"language"`
	Location   Location               `json:"location"`
	Name       string                 `json:"name"`
	Photo      []PhotoSize            `json:"photo"`
	Size       int                    `json:"size"`
	Summary    RichText               `json:"summary"`
	Text       RichText               `json:"text"`
	Type       string                 `json:"type"`
	Video      Video                  `json:"video"`
	VoiceNote  Voice                  `json:"voice_note"`
	Width      int64                  `json:"width"`
	Zoom       int                    `json:"zoom"`
}

func (x RichBlock) Kind() int {
	switch x.Type {
	case "paragraph":
		return TypeRichBlockParagraph
	case "heading":
		return TypeRichBlockSectionHeading
	case "pre":
		return TypeRichBlockPreformatted
	case "footer":
		return TypeRichBlockFooter
	case "divider":
		return TypeRichBlockDivider
	case "mathematical_expression":
		return TypeRichBlockMathematicalExpression
	case "anchor":
		return TypeRichBlockAnchor
	case "list":
		return TypeRichBlockList
	case "blockquote":
		return TypeRichBlockBlockQuotation
	case "pullquote":
		return TypeRichBlockPullQuotation
	case "collage":
		return TypeRichBlockCollage
	case "slideshow":
		return TypeRichBlockSlideshow
	case "table":
		return TypeRichBlockTable
	case "details":
		return TypeRichBlockDetails
	case "map":
		return TypeRichBlockMap
	case "animation":
		return TypeRichBlockAnimation
	case "audio":
		return TypeRichBlockAudio
	case "photo":
		return TypeRichBlockPhoto
	case "video":
		return TypeRichBlockVideo
	case "voice_note":
		return TypeRichBlockVoiceNote
	case "thinking":
		return TypeRichBlockThinking
	default:
		return -1
	}
}
