// Code AutoGenerated; DO NOT EDIT.

package types

// RichBlockTableCell Cell in a table.
type RichBlockTableCell struct {
	Align    string    `json:"align"`
	Colspan  int       `json:"colspan,omitempty"`
	IsHeader bool      `json:"is_header,omitempty"`
	Rowspan  int       `json:"rowspan,omitempty"`
	Text     *RichText `json:"text,omitempty"`
	Valign   string    `json:"valign"`
}
