// Code AutoGenerated; DO NOT EDIT.

package types

import (
	"bytes"
	"encoding/json"
)

// RichText Represents a rich formatted text
// Currently, it can be either a String for plain text, an Array of RichText, or any of the following types:
//   - RichTextBold
//   - RichTextItalic
//   - RichTextUnderline
//   - RichTextStrikethrough
//   - RichTextSpoiler
//   - RichTextDateTime
//   - RichTextTextMention
//   - RichTextSubscript
//   - RichTextSuperscript
//   - RichTextMarked
//   - RichTextCode
//   - RichTextCustomEmoji
//   - RichTextMathematicalExpression
//   - RichTextUrl
//   - RichTextEmailAddress
//   - RichTextPhoneNumber
//   - RichTextBankCardNumber
//   - RichTextMention
//   - RichTextHashtag
//   - RichTextCashtag
//   - RichTextBotCommand
//   - RichTextAnchor
//   - RichTextAnchorLink
//   - RichTextReference
//   - RichTextReferenceLink
type RichText struct {
	AlternativeText string        `json:"alternative_text"`
	AnchorName      string        `json:"anchor_name"`
	BankCardNumber  string        `json:"bank_card_number"`
	BotCommand      string        `json:"bot_command"`
	Cashtag         string        `json:"cashtag"`
	CustomEmojiID   string        `json:"custom_emoji_id"`
	DateTimeFormat  string        `json:"date_time_format"`
	EmailAddress    string        `json:"email_address"`
	Expression      string        `json:"expression"`
	Hashtag         string        `json:"hashtag"`
	Name            string        `json:"name"`
	PhoneNumber     string        `json:"phone_number"`
	ReferenceName   string        `json:"reference_name"`
	Text            RichTextValue `json:"text"`
	Type            string        `json:"type"`
	UnixTime        int           `json:"unix_time"`
	URL             string        `json:"url"`
	User            User          `json:"user"`
	Username        string        `json:"username"`
}

func (x RichText) Kind() int {
	switch x.Type {
	case "bold":
		return TypeRichTextBold
	case "italic":
		return TypeRichTextItalic
	case "underline":
		return TypeRichTextUnderline
	case "strikethrough":
		return TypeRichTextStrikethrough
	case "spoiler":
		return TypeRichTextSpoiler
	case "date_time":
		return TypeRichTextDateTime
	case "text_mention":
		return TypeRichTextTextMention
	case "subscript":
		return TypeRichTextSubscript
	case "superscript":
		return TypeRichTextSuperscript
	case "marked":
		return TypeRichTextMarked
	case "code":
		return TypeRichTextCode
	case "custom_emoji":
		return TypeRichTextCustomEmoji
	case "mathematical_expression":
		return TypeRichTextMathematicalExpression
	case "url":
		return TypeRichTextUrl
	case "email_address":
		return TypeRichTextEmailAddress
	case "phone_number":
		return TypeRichTextPhoneNumber
	case "bank_card_number":
		return TypeRichTextBankCardNumber
	case "mention":
		return TypeRichTextMention
	case "hashtag":
		return TypeRichTextHashtag
	case "cashtag":
		return TypeRichTextCashtag
	case "bot_command":
		return TypeRichTextBotCommand
	case "anchor":
		return TypeRichTextAnchor
	case "anchor_link":
		return TypeRichTextAnchorLink
	case "reference":
		return TypeRichTextReference
	case "reference_link":
		return TypeRichTextReferenceLink
	default:
		return -1
	}
}

// RichTextValue is either RichTextPlain, RichTextArray or RichText
type RichTextValue interface {
	Kind() int
}

type RichTextPlain string

func (x RichTextPlain) Kind() int {
	return TypeRichTextPlain
}

type RichTextArray []RichTextValue

func (x RichTextArray) Kind() int {
	return TypeRichTextArray
}

func ParseRichTextValue(data []byte) (RichTextValue, error) {
	data = bytes.TrimSpace(data)
	if len(data) == 0 || string(data) == "null" {
		return nil, nil
	}
	if data[0] == '"' {
		var plain string
		if err := json.Unmarshal(data, &plain); err != nil {
			return nil, err
		}
		return RichTextPlain(plain), nil
	}
	if data[0] == '[' {
		var rawItems []json.RawMessage
		if err := json.Unmarshal(data, &rawItems); err != nil {
			return nil, err
		}
		items := make(RichTextArray, 0, len(rawItems))
		for _, rawItem := range rawItems {
			item, err := ParseRichTextValue(rawItem)
			if err != nil {
				return nil, err
			}
			items = append(items, item)
		}
		return items, nil
	}
	var item RichText
	if err := json.Unmarshal(data, &item); err != nil {
		return nil, err
	}
	return item, nil
}

func (entity *RichText) UnmarshalJSON(data []byte) error {
	var alias struct {
		AlternativeText string          `json:"alternative_text"`
		AnchorName      string          `json:"anchor_name"`
		BankCardNumber  string          `json:"bank_card_number"`
		BotCommand      string          `json:"bot_command"`
		Cashtag         string          `json:"cashtag"`
		CustomEmojiID   string          `json:"custom_emoji_id"`
		DateTimeFormat  string          `json:"date_time_format"`
		EmailAddress    string          `json:"email_address"`
		Expression      string          `json:"expression"`
		Hashtag         string          `json:"hashtag"`
		Name            string          `json:"name"`
		PhoneNumber     string          `json:"phone_number"`
		ReferenceName   string          `json:"reference_name"`
		Text            json.RawMessage `json:"text"`
		Type            string          `json:"type"`
		UnixTime        int             `json:"unix_time"`
		URL             string          `json:"url"`
		User            User            `json:"user"`
		Username        string          `json:"username"`
	}
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	var err error
	entity.AlternativeText = alias.AlternativeText
	entity.AnchorName = alias.AnchorName
	entity.BankCardNumber = alias.BankCardNumber
	entity.BotCommand = alias.BotCommand
	entity.Cashtag = alias.Cashtag
	entity.CustomEmojiID = alias.CustomEmojiID
	entity.DateTimeFormat = alias.DateTimeFormat
	entity.EmailAddress = alias.EmailAddress
	entity.Expression = alias.Expression
	entity.Hashtag = alias.Hashtag
	entity.Name = alias.Name
	entity.PhoneNumber = alias.PhoneNumber
	entity.ReferenceName = alias.ReferenceName
	if entity.Text, err = ParseRichTextValue(alias.Text); err != nil {
		return err
	}
	entity.Type = alias.Type
	entity.UnixTime = alias.UnixTime
	entity.URL = alias.URL
	entity.User = alias.User
	entity.Username = alias.Username
	return nil
}
