// Code AutoGenerated; DO NOT EDIT.

package types

import "encoding/json"

// RichBlock Represents a block in a rich formatted message
// Currently, it can be any of the following types:
//   - RichBlockParagraph
//   - RichBlockSectionHeading
//   - RichBlockPreformatted
//   - RichBlockFooter
//   - RichBlockDivider
//   - RichBlockMathematicalExpression
//   - RichBlockAnchor
//   - RichBlockList
//   - RichBlockBlockQuotation
//   - RichBlockPullQuotation
//   - RichBlockCollage
//   - RichBlockSlideshow
//   - RichBlockTable
//   - RichBlockDetails
//   - RichBlockMap
//   - RichBlockAnimation
//   - RichBlockAudio
//   - RichBlockPhoto
//   - RichBlockVideo
//   - RichBlockVoiceNote
//   - RichBlockThinking
type RichBlock struct {
	Animation  Animation              `json:"animation"`
	Audio      Audio                  `json:"audio"`
	Blocks     []RichBlock            `json:"blocks"`
	Caption    *RichBlockCaption      `json:"caption"`
	Cells      [][]RichBlockTableCell `json:"cells"`
	Credit     RichTextValue          `json:"credit"`
	Expression string                 `json:"expression"`
	HasSpoiler bool                   `json:"has_spoiler"`
	Height     int                    `json:"height"`
	IsBordered bool                   `json:"is_bordered"`
	IsOpen     bool                   `json:"is_open"`
	IsStriped  bool                   `json:"is_striped"`
	Items      []RichBlockListItem    `json:"items"`
	Language   string                 `json:"language"`
	Location   Location               `json:"location"`
	Name       string                 `json:"name"`
	Photo      []PhotoSize            `json:"photo"`
	Size       int                    `json:"size"`
	Summary    RichTextValue          `json:"summary"`
	Text       RichTextValue          `json:"text"`
	Type       string                 `json:"type"`
	Video      Video                  `json:"video"`
	VoiceNote  Voice                  `json:"voice_note"`
	Width      int64                  `json:"width"`
	Zoom       int                    `json:"zoom"`
}

func (x RichBlock) Kind() int {
	switch x.Type {
	case "paragraph":
		return TypeRichBlockParagraph
	case "heading":
		return TypeRichBlockSectionHeading
	case "pre":
		return TypeRichBlockPreformatted
	case "footer":
		return TypeRichBlockFooter
	case "divider":
		return TypeRichBlockDivider
	case "mathematical_expression":
		return TypeRichBlockMathematicalExpression
	case "anchor":
		return TypeRichBlockAnchor
	case "list":
		return TypeRichBlockList
	case "blockquote":
		return TypeRichBlockBlockQuotation
	case "pullquote":
		return TypeRichBlockPullQuotation
	case "collage":
		return TypeRichBlockCollage
	case "slideshow":
		return TypeRichBlockSlideshow
	case "table":
		return TypeRichBlockTable
	case "details":
		return TypeRichBlockDetails
	case "map":
		return TypeRichBlockMap
	case "animation":
		return TypeRichBlockAnimation
	case "audio":
		return TypeRichBlockAudio
	case "photo":
		return TypeRichBlockPhoto
	case "video":
		return TypeRichBlockVideo
	case "voice_note":
		return TypeRichBlockVoiceNote
	case "thinking":
		return TypeRichBlockThinking
	default:
		return -1
	}
}

func (entity *RichBlock) UnmarshalJSON(data []byte) error {
	var alias struct {
		Animation  Animation              `json:"animation"`
		Audio      Audio                  `json:"audio"`
		Blocks     []RichBlock            `json:"blocks"`
		Caption    *RichBlockCaption      `json:"caption"`
		Cells      [][]RichBlockTableCell `json:"cells"`
		Credit     json.RawMessage        `json:"credit"`
		Expression string                 `json:"expression"`
		HasSpoiler bool                   `json:"has_spoiler"`
		Height     int                    `json:"height"`
		IsBordered bool                   `json:"is_bordered"`
		IsOpen     bool                   `json:"is_open"`
		IsStriped  bool                   `json:"is_striped"`
		Items      []RichBlockListItem    `json:"items"`
		Language   string                 `json:"language"`
		Location   Location               `json:"location"`
		Name       string                 `json:"name"`
		Photo      []PhotoSize            `json:"photo"`
		Size       int                    `json:"size"`
		Summary    json.RawMessage        `json:"summary"`
		Text       json.RawMessage        `json:"text"`
		Type       string                 `json:"type"`
		Video      Video                  `json:"video"`
		VoiceNote  Voice                  `json:"voice_note"`
		Width      int64                  `json:"width"`
		Zoom       int                    `json:"zoom"`
	}
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	var err error
	entity.Animation = alias.Animation
	entity.Audio = alias.Audio
	entity.Blocks = alias.Blocks
	entity.Caption = alias.Caption
	entity.Cells = alias.Cells
	if entity.Credit, err = ParseRichTextValue(alias.Credit); err != nil {
		return err
	}
	entity.Expression = alias.Expression
	entity.HasSpoiler = alias.HasSpoiler
	entity.Height = alias.Height
	entity.IsBordered = alias.IsBordered
	entity.IsOpen = alias.IsOpen
	entity.IsStriped = alias.IsStriped
	entity.Items = alias.Items
	entity.Language = alias.Language
	entity.Location = alias.Location
	entity.Name = alias.Name
	entity.Photo = alias.Photo
	entity.Size = alias.Size
	if entity.Summary, err = ParseRichTextValue(alias.Summary); err != nil {
		return err
	}
	if entity.Text, err = ParseRichTextValue(alias.Text); err != nil {
		return err
	}
	entity.Type = alias.Type
	entity.Video = alias.Video
	entity.VoiceNote = alias.VoiceNote
	entity.Width = alias.Width
	entity.Zoom = alias.Zoom
	return nil
}
