// Code AutoGenerated; DO NOT EDIT.

package types

// RichMessage Rich formatted message.
type RichMessage struct {
	Blocks []RichBlock `json:"blocks,omitempty"`
	IsRtl  bool        `json:"is_rtl,omitempty"`
}
