// Code AutoGenerated; DO NOT EDIT.

package types

// RichBlockCaption Caption of a rich formatted block.
type RichBlockCaption struct {
	Credit *RichText `json:"credit,omitempty"`
	Text   RichText  `json:"text"`
}
