// Code AutoGenerated; DO NOT EDIT.

package types

// StarAmount Describes an amount of Telegram Stars.
type StarAmount struct {
	Amount         int `json:"amount"`
	NanostarAmount int `json:"nanostar_amount,omitempty"`
}
