// Code AutoGenerated; DO NOT EDIT.

package types

// StoryAreaPosition Describes the position of a clickable area within a story.
type StoryAreaPosition struct {
	CornerRadiusPercentage float64 `json:"corner_radius_percentage"`
	HeightPercentage       float64 `json:"height_percentage"`
	RotationAngle          float64 `json:"rotation_angle"`
	WidthPercentage        float64 `json:"width_percentage"`
	XPercentage            float64 `json:"x_percentage"`
	YPercentage            float64 `json:"y_percentage"`
}
