// Code AutoGenerated; DO NOT EDIT.

package types

// StoryArea Describes a clickable area on a story media.
type StoryArea struct {
	Position StoryAreaPosition `json:"position"`
	Type     StoryAreaType     `json:"type"`
}
