// Code AutoGenerated; DO NOT EDIT.

package types

// SuccessfulPayment This object contains basic information about a successful payment.
type SuccessfulPayment struct {
	Currency                string     `json:"currency"`
	InvoicePayload          string     `json:"invoice_payload"`
	OrderInfo               *OrderInfo `json:"order_info,omitempty"`
	ProviderPaymentChargeID string     `json:"provider_payment_charge_id"`
	ShippingOptionID        string     `json:"shipping_option_id,omitempty"`
	TelegramPaymentChargeID string     `json:"telegram_payment_charge_id"`
	TotalAmount             int        `json:"total_amount"`
}
