// Code AutoGenerated; DO NOT EDIT.

package types

// SuggestedPostPaid Describes a service message about a successful payment for a suggested post.
type SuggestedPostPaid struct {
	Amount               int         `json:"amount,omitempty"`
	Currency             string      `json:"currency"`
	StarAmount           *StarAmount `json:"star_amount,omitempty"`
	SuggestedPostMessage *Message    `json:"suggested_post_message,omitempty"`
}
