// Code AutoGenerated; DO NOT EDIT.

package types

// SuggestedPostApprovalFailed Describes a service message about the failed approval of a suggested post
// Currently, only caused by insufficient user funds at the time of approval.
type SuggestedPostApprovalFailed struct {
	Price                SuggestedPostPrice `json:"price"`
	SuggestedPostMessage *Message           `json:"suggested_post_message,omitempty"`
}
