// Code AutoGenerated; DO NOT EDIT.

package types

// SuggestedPostRefunded Describes a service message about a payment refund for a suggested post.
type SuggestedPostRefunded struct {
	Reason               string   `json:"reason"`
	SuggestedPostMessage *Message `json:"suggested_post_message,omitempty"`
}
