// Code AutoGenerated; DO NOT EDIT.

package types

// SuggestedPostParameters Contains parameters of a post that is being suggested by the bot.
type SuggestedPostParameters struct {
	Price    *SuggestedPostPrice `json:"price,omitempty"`
	SendDate int64               `json:"send_date,omitempty"`
}
