// Code AutoGenerated; DO NOT EDIT.

package types

// SuggestedPostDeclined Describes a service message about the rejection of a suggested post.
type SuggestedPostDeclined struct {
	Comment              string   `json:"comment,omitempty"`
	SuggestedPostMessage *Message `json:"suggested_post_message,omitempty"`
}
