// Code AutoGenerated; DO NOT EDIT.

package types

// SuggestedPostPrice Desribes price of a suggested post.
type SuggestedPostPrice struct {
	Amount   int    `json:"amount"`
	Currency string `json:"currency"`
}
