// Code AutoGenerated; DO NOT EDIT.

package types

// SuggestedPostApproved Describes a service message about the approval of a suggested post.
type SuggestedPostApproved struct {
	Price                *SuggestedPostPrice `json:"price,omitempty"`
	SendDate             int64               `json:"send_date"`
	SuggestedPostMessage *Message            `json:"suggested_post_message,omitempty"`
}
