// Code AutoGenerated; DO NOT EDIT.

package types

// SwitchInlineQueryChosenChat Represents an inline button that switches the current user to inline mode in a chosen chat, with an optional default inline query.
type SwitchInlineQueryChosenChat struct {
	AllowBotChats     bool   `json:"allow_bot_chats,omitempty"`
	AllowChannelChats bool   `json:"allow_channel_chats,omitempty"`
	AllowGroupChats   bool   `json:"allow_group_chats,omitempty"`
	AllowUserChats    bool   `json:"allow_user_chats,omitempty"`
	Query             string `json:"query,omitempty"`
}
