// Code AutoGenerated; DO NOT EDIT.

package types

// TextQuote This object contains information about the quoted part of a message that is replied to by the given message.
type TextQuote struct {
	Entities []MessageEntity `json:"entities,omitempty"`
	IsManual bool            `json:"is_manual,omitempty"`
	Position int             `json:"position"`
	Text     string          `json:"text"`
}
