// Code AutoGenerated; DO NOT EDIT.

package types

// TransactionPartner This object describes the source of a transaction, or its recipient for outgoing transactions
// Currently, it can be one of
//   - TransactionPartnerUser
//   - TransactionPartnerChat
//   - TransactionPartnerAffiliateProgram
//   - TransactionPartnerFragment
//   - TransactionPartnerTelegramAds
//   - TransactionPartnerTelegramApi
//   - TransactionPartnerOther
type TransactionPartner struct {
	Affiliate          *AffiliateInfo          `json:"affiliate"`
	Chat               Chat                    `json:"chat"`
	CommissionPerMille int                     `json:"commission_per_mille"`
	Gift               *Gift                   `json:"gift"`
	InvoicePayload     string                  `json:"invoice_payload"`
	PaidMedia          []PaidMedia             `json:"paid_media"`
	PaidMediaPayload   string                  `json:"paid_media_payload"`
	RequestCount       int                     `json:"request_count"`
	SponsorUser        *User                   `json:"sponsor_user"`
	SubscriptionPeriod int                     `json:"subscription_period"`
	Type               string                  `json:"type"`
	User               User                    `json:"user"`
	WithdrawalState    *RevenueWithdrawalState `json:"withdrawal_state"`
}

func (x TransactionPartner) Kind() int {
	switch x.Type {
	case "user":
		return TypeTransactionPartnerUser
	case "chat":
		return TypeTransactionPartnerChat
	case "affiliate_program":
		return TypeTransactionPartnerAffiliateProgram
	case "fragment":
		return TypeTransactionPartnerFragment
	case "telegram_ads":
		return TypeTransactionPartnerTelegramAds
	case "telegram_api":
		return TypeTransactionPartnerTelegramApi
	case "other":
		return TypeTransactionPartnerOther
	default:
		return -1
	}
}
