// Code AutoGenerated; DO NOT EDIT.

package types

// UniqueGiftBackdropColors This object describes the colors of the backdrop of a unique gift.
type UniqueGiftBackdropColors struct {
	CenterColor int `json:"center_color"`
	EdgeColor   int `json:"edge_color"`
	SymbolColor int `json:"symbol_color"`
	TextColor   int `json:"text_color"`
}
