// Code AutoGenerated; DO NOT EDIT.

package types

// UniqueGiftSymbol This object describes the symbol shown on the pattern of a unique gift.
type UniqueGiftSymbol struct {
	Name           string  `json:"name"`
	RarityPerMille int     `json:"rarity_per_mille"`
	Sticker        Sticker `json:"sticker"`
}
