// Code AutoGenerated; DO NOT EDIT.

package types

// UniqueGiftBackdrop This object describes the backdrop of a unique gift.
type UniqueGiftBackdrop struct {
	Colors         UniqueGiftBackdropColors `json:"colors"`
	Name           string                   `json:"name"`
	RarityPerMille int                      `json:"rarity_per_mille"`
}
