// Code AutoGenerated; DO NOT EDIT.

package types

// UniqueGift This object describes a unique gift that was upgraded from a regular gift.
type UniqueGift struct {
	Backdrop UniqueGiftBackdrop `json:"backdrop"`
	BaseName string             `json:"base_name"`
	Model    UniqueGiftModel    `json:"model"`
	Name     string             `json:"name"`
	Number   int                `json:"number"`
	Symbol   UniqueGiftSymbol   `json:"symbol"`
}
