// Code AutoGenerated; DO NOT EDIT.

package types

// UserProfileAudios Represents the audios displayed on a user's profile.
type UserProfileAudios struct {
	Audios     []Audio `json:"audios,omitempty"`
	TotalCount int     `json:"total_count"`
}
