// Code AutoGenerated; DO NOT EDIT.

package types

// UserProfilePhotos This object represent a user's profile pictures.
type UserProfilePhotos struct {
	Photos [][]PhotoSize `json:"photos,omitempty"`
	TotalCount int `json:"total_count"`
}
