// Code AutoGenerated; DO NOT EDIT.

package types

// UserChatBoosts Represents a list of boosts added to a chat by a user.
type UserChatBoosts struct {
	Boosts []ChatBoost `json:"boosts,omitempty"`
}
