// Code AutoGenerated; DO NOT EDIT.

package types

// Venue Represents a venue.
type Venue struct {
	Address         string   `json:"address"`
	FoursquareID    string   `json:"foursquare_id,omitempty"`
	FoursquareType  string   `json:"foursquare_type,omitempty"`
	GooglePlaceID   string   `json:"google_place_id,omitempty"`
	GooglePlaceType string   `json:"google_place_type,omitempty"`
	Location        Location `json:"location"`
	Title           string   `json:"title"`
}
