// Code AutoGenerated; DO NOT EDIT.

package types

// VideoChatEnded Represents a service message about a video chat ended in the chat.
type VideoChatEnded struct {
	Duration int `json:"duration"`
}
