// Code AutoGenerated; DO NOT EDIT.

package types

// VideoChatStarted Represents a service message about a video chat started in the chat
// Currently holds no information.
type VideoChatStarted interface{}
