// Code AutoGenerated; DO NOT EDIT.

package types

// VideoQuality Represents a video file of a specific quality.
type VideoQuality struct {
	Codec        string `json:"codec"`
	FileID       string `json:"file_id"`
	FileSize     int    `json:"file_size,omitempty"`
	FileUniqueID string `json:"file_unique_id"`
	Height       int    `json:"height"`
	Width        int64  `json:"width"`
}
