// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"gobotapi/types"
	rawTypes "gobotapi/types/raw"
)

// AddStickerToSet Use this method to add a new sticker to a set created by the bot
// Emoji sticker sets can have up to 200 stickers
// Other sticker sets can have up to 120 stickers
// Returns True on success.
type AddStickerToSet struct {
	Name    string             `json:"name"`
	Sticker types.InputSticker `json:"sticker"`
	UserID  int64              `json:"user_id"`
}

func (entity *AddStickerToSet) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *AddStickerToSet) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (AddStickerToSet) MethodName() string {
	return "addStickerToSet"
}

func (AddStickerToSet) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
