// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// AnswerChatJoinRequestQuery Use this method to process a received chat join request query
// Returns True on success.
type AnswerChatJoinRequestQuery struct {
	ChatJoinRequestQueryID string `json:"chat_join_request_query_id"`
	Result                 string `json:"result"`
}

func (entity *AnswerChatJoinRequestQuery) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *AnswerChatJoinRequestQuery) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (AnswerChatJoinRequestQuery) MethodName() string {
	return "answerChatJoinRequestQuery"
}

func (AnswerChatJoinRequestQuery) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
