// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// BanChatMember Use this method to ban a user in a group, a supergroup or a channel
// In the case of supergroups and channels, the user will not be able to return to the chat on their own using invite links, etc., unless unbanned first
// The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights
// Returns True on success.
type BanChatMember struct {
	ChatID         any   `json:"chat_id"`
	RevokeMessages bool  `json:"revoke_messages,omitempty"`
	UntilDate      int64 `json:"until_date,omitempty"`
	UserID         int64 `json:"user_id"`
}

func (entity *BanChatMember) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *BanChatMember) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity BanChatMember) MarshalJSON() ([]byte, error) {
	if !reflect.DeepEqual(entity.ChatID, nil) {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 BanChatMember
	return json.Marshal((x0)(entity))
}

func (BanChatMember) MethodName() string {
	return "banChatMember"
}

func (BanChatMember) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
