// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/Squirrel-Network/gobotapi/types"
	rawTypes "github.com/Squirrel-Network/gobotapi/types/raw"
)

// DeclineChatJoinRequest Use this method to decline a chat join request
// The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right
// Returns True on success.
type DeclineChatJoinRequest struct {
	ChatID any   `json:"chat_id"`
	UserID int64 `json:"user_id"`
}

func (entity *DeclineChatJoinRequest) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *DeclineChatJoinRequest) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity DeclineChatJoinRequest) MarshalJSON() ([]byte, error) {
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 DeclineChatJoinRequest
	return json.Marshal((x0)(entity))
}

func (DeclineChatJoinRequest) MethodName() string {
	return "declineChatJoinRequest"
}

func (DeclineChatJoinRequest) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
