// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// DeclineSuggestedPost Use this method to decline a suggested post in a direct messages chat
// The bot must have the 'can_manage_direct_messages' administrator right in the corresponding channel chat
// Returns True on success.
type DeclineSuggestedPost struct {
	ChatID    int64  `json:"chat_id"`
	Comment   string `json:"comment,omitempty"`
	MessageID int64  `json:"message_id"`
}

func (entity *DeclineSuggestedPost) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *DeclineSuggestedPost) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (DeclineSuggestedPost) MethodName() string {
	return "declineSuggestedPost"
}

func (DeclineSuggestedPost) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
