// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// DeleteMessages Use this method to delete multiple messages simultaneously
// If some of the specified messages can't be found, they are skipped
// Returns True on success.
type DeleteMessages struct {
	ChatID     any     `json:"chat_id"`
	MessageIDs []int64 `json:"message_ids,omitempty"`
}

func (entity *DeleteMessages) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *DeleteMessages) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity DeleteMessages) MarshalJSON() ([]byte, error) {
	if !reflect.DeepEqual(entity.ChatID, nil) {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 DeleteMessages
	return json.Marshal((x0)(entity))
}

func (DeleteMessages) MethodName() string {
	return "deleteMessages"
}

func (DeleteMessages) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
