// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// DeleteMessageReaction Use this method to remove a reaction from a message in a group or a supergroup chat
// The bot must have the 'can_delete_messages' administrator right in the chat
// Returns True on success.
type DeleteMessageReaction struct {
	ActorChatID int64 `json:"actor_chat_id,omitempty"`
	ChatID      any   `json:"chat_id"`
	MessageID   int64 `json:"message_id"`
	UserID      int64 `json:"user_id,omitempty"`
}

func (entity *DeleteMessageReaction) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *DeleteMessageReaction) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity DeleteMessageReaction) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 DeleteMessageReaction
	return json.Marshal((x0)(entity))
}

func (DeleteMessageReaction) MethodName() string {
	return "deleteMessageReaction"
}

func (DeleteMessageReaction) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
