// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// DeleteEphemeralMessage Use this method to delete an ephemeral message
// Note that it is not guaranteed that the user will receive the message deletion event, especially if they are offline
// Returns True on success.
type DeleteEphemeralMessage struct {
	ChatID             any   `json:"chat_id"`
	EphemeralMessageID int64 `json:"ephemeral_message_id"`
	ReceiverUserID     int64 `json:"receiver_user_id"`
}

func (entity *DeleteEphemeralMessage) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *DeleteEphemeralMessage) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity DeleteEphemeralMessage) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 DeleteEphemeralMessage
	return json.Marshal((x0)(entity))
}

func (DeleteEphemeralMessage) MethodName() string {
	return "deleteEphemeralMessage"
}

func (DeleteEphemeralMessage) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
