// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// DeleteStory Deletes a story previously posted by the bot on behalf of a managed business account
// Requires the can_manage_stories business bot right
// Returns True on success.
type DeleteStory struct {
	BusinessConnectionID string `json:"business_connection_id"`
	StoryID              int64  `json:"story_id"`
}

func (entity *DeleteStory) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *DeleteStory) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (DeleteStory) MethodName() string {
	return "deleteStory"
}

func (DeleteStory) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
