// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// EditChatSubscriptionInviteLink Use this method to edit a subscription invite link created by the bot
// The bot must have the can_invite_users administrator rights
// Returns the edited invite link as a ChatInviteLink object.
type EditChatSubscriptionInviteLink struct {
	ChatID     any    `json:"chat_id"`
	InviteLink string `json:"invite_link"`
	Name       string `json:"name,omitempty"`
}

func (entity *EditChatSubscriptionInviteLink) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *EditChatSubscriptionInviteLink) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity EditChatSubscriptionInviteLink) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 EditChatSubscriptionInviteLink
	return json.Marshal((x0)(entity))
}

func (EditChatSubscriptionInviteLink) MethodName() string {
	return "editChatSubscriptionInviteLink"
}

func (EditChatSubscriptionInviteLink) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.ChatInviteLink `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeChatInviteLink,
		Result: x1.Result,
	}
	return &result, nil
}
