// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// EditEphemeralMessageMedia Use this method to edit the media of an ephemeral message
// Note that it is not guaranteed that the user will receive the message edit event, especially if they are offline
// On success, True is returned.
type EditEphemeralMessageMedia struct {
	ChatID             any                         `json:"chat_id"`
	EphemeralMessageID int64                       `json:"ephemeral_message_id"`
	Media              types.InputMedia            `json:"media"`
	ReceiverUserID     int64                       `json:"receiver_user_id"`
	ReplyMarkup        *types.InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	Progress           rawTypes.ProgressCallable   `json:"-"`
}

func (entity *EditEphemeralMessageMedia) ProgressCallable() rawTypes.ProgressCallable {
	return entity.Progress
}

func (entity *EditEphemeralMessageMedia) Files() map[string]rawTypes.InputFile {
	files := make(map[string]rawTypes.InputFile)
	for k, v := range entity.Media.(rawTypes.InputMediaFiles).Files() {
		files[k] = v
		if k == "thumbnail" {
			entity.Media.SetAttachmentThumb(k)
		} else {
			entity.Media.SetAttachment(k)
		}
	}
	return files
}

func (entity EditEphemeralMessageMedia) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if nilCheck(entity.ReplyMarkup) {
		entity.ReplyMarkup = nil
	}
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 EditEphemeralMessageMedia
	return json.Marshal((x0)(entity))
}

func (EditEphemeralMessageMedia) MethodName() string {
	return "editEphemeralMessageMedia"
}

func (EditEphemeralMessageMedia) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
