// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// EditEphemeralMessageText Use this method to edit an ephemeral text message
// Note that it is not guaranteed that the user will receive the message edit event, especially if they are offline
// On success, True is returned.
type EditEphemeralMessageText struct {
	ChatID             any                         `json:"chat_id"`
	Entities           []types.MessageEntity       `json:"entities,omitempty"`
	EphemeralMessageID int64                       `json:"ephemeral_message_id"`
	LinkPreviewOptions *types.LinkPreviewOptions   `json:"link_preview_options,omitempty"`
	ParseMode          string                      `json:"parse_mode,omitempty"`
	ReceiverUserID     int64                       `json:"receiver_user_id"`
	ReplyMarkup        *types.InlineKeyboardMarkup `json:"reply_markup,omitempty"`
	Text               string                      `json:"text"`
}

func (entity *EditEphemeralMessageText) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *EditEphemeralMessageText) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity EditEphemeralMessageText) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if nilCheck(entity.LinkPreviewOptions) {
		entity.LinkPreviewOptions = nil
	}
	if nilCheck(entity.ReplyMarkup) {
		entity.ReplyMarkup = nil
	}
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 EditEphemeralMessageText
	return json.Marshal((x0)(entity))
}

func (EditEphemeralMessageText) MethodName() string {
	return "editEphemeralMessageText"
}

func (EditEphemeralMessageText) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
