// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// EditUserStarSubscription Allows the bot to cancel or re-enable extension of a subscription paid in Telegram Stars
// Returns True on success.
type EditUserStarSubscription struct {
	IsCanceled              bool   `json:"is_canceled"`
	TelegramPaymentChargeID string `json:"telegram_payment_charge_id"`
	UserID                  int64  `json:"user_id"`
}

func (entity *EditUserStarSubscription) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *EditUserStarSubscription) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (EditUserStarSubscription) MethodName() string {
	return "editUserStarSubscription"
}

func (EditUserStarSubscription) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
