// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// EditMessageChecklist Use this method to edit a checklist on behalf of a connected business account
// On success, the edited Message is returned.
type EditMessageChecklist struct {
	BusinessConnectionID string                      `json:"business_connection_id"`
	ChatID               int64                       `json:"chat_id"`
	Checklist            types.InputChecklist        `json:"checklist"`
	MessageID            int64                       `json:"message_id"`
	ReplyMarkup          *types.InlineKeyboardMarkup `json:"reply_markup,omitempty"`
}

func (entity *EditMessageChecklist) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *EditMessageChecklist) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity EditMessageChecklist) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if nilCheck(entity.ReplyMarkup) {
		entity.ReplyMarkup = nil
	}
	type x0 EditMessageChecklist
	return json.Marshal((x0)(entity))
}

func (EditMessageChecklist) MethodName() string {
	return "editMessageChecklist"
}

func (EditMessageChecklist) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.Message `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeMessage,
		Result: x1.Result,
	}
	return &result, nil
}
