// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// ExportChatInviteLink Use this method to generate a new primary invite link for a chat; any previously generated primary link is revoked
// The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights
// Returns the new invite link as String on success.
type ExportChatInviteLink struct {
	ChatID any `json:"chat_id"`
}

func (entity *ExportChatInviteLink) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *ExportChatInviteLink) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity ExportChatInviteLink) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 ExportChatInviteLink
	return json.Marshal((x0)(entity))
}

func (ExportChatInviteLink) MethodName() string {
	return "exportChatInviteLink"
}

func (ExportChatInviteLink) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result string `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeString,
		Result: x1.Result,
	}
	return &result, nil
}
