// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/Squirrel-Network/gobotapi/types"
	rawTypes "github.com/Squirrel-Network/gobotapi/types/raw"
)

// GetChatMember Use this method to get information about a member of a chat
// Returns a ChatMember object on success.
type GetChatMember struct {
	ChatID any   `json:"chat_id"`
	UserID int64 `json:"user_id"`
}

func (entity *GetChatMember) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetChatMember) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity GetChatMember) MarshalJSON() ([]byte, error) {
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 GetChatMember
	return json.Marshal((x0)(entity))
}

func (GetChatMember) MethodName() string {
	return "getChatMember"
}

func (GetChatMember) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.ChatMember `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeChatMember,
		Result: x1.Result,
	}
	return &result, nil
}
