// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// GetStarTransactions Returns the bot's Telegram Star transactions in chronological order
// On success, returns a StarTransactions object.
type GetStarTransactions struct {
	Limit  int `json:"limit,omitempty"`
	Offset int `json:"offset,omitempty"`
}

func (entity *GetStarTransactions) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetStarTransactions) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (GetStarTransactions) MethodName() string {
	return "getStarTransactions"
}

func (GetStarTransactions) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.StarTransactions `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeStarTransactions,
		Result: x1.Result,
	}
	return &result, nil
}
