// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/Squirrel-Network/gobotapi/types"
	rawTypes "github.com/Squirrel-Network/gobotapi/types/raw"
)

// GetChat Use this method to get up to date information about the chat (current name of the user for one-on-one conversations, current username of a user, group or channel, etc.)
// Returns a Chat object on success.
type GetChat struct {
	ChatID any `json:"chat_id"`
}

func (entity *GetChat) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetChat) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity GetChat) MarshalJSON() ([]byte, error) {
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 GetChat
	return json.Marshal((x0)(entity))
}

func (GetChat) MethodName() string {
	return "getChat"
}

func (GetChat) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.Chat `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeChat,
		Result: x1.Result,
	}
	return &result, nil
}
