// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"gobotapi/types"
	rawTypes "gobotapi/types/raw"
)

// GetForumTopicIconStickers Use this method to get custom emoji stickers, which can be used as a forum topic icon by any user
// Requires no parameters
// Returns an Array of Sticker objects.
type GetForumTopicIconStickers struct{}

func (entity *GetForumTopicIconStickers) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetForumTopicIconStickers) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (GetForumTopicIconStickers) MethodName() string {
	return "getForumTopicIconStickers"
}

func (GetForumTopicIconStickers) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result []types.Sticker `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeArrayOfSticker,
		Result: x1.Result,
	}
	return &result, nil
}
