// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// GetManagedBotToken Use this method to get the token of a managed bot
// Returns the token as String on success.
type GetManagedBotToken struct {
	UserID int64 `json:"user_id"`
}

func (entity *GetManagedBotToken) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetManagedBotToken) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (GetManagedBotToken) MethodName() string {
	return "getManagedBotToken"
}

func (GetManagedBotToken) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result string `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeString,
		Result: x1.Result,
	}
	return &result, nil
}
