// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// GetChatAdministrators Use this method to get a list of administrators in a chat, which aren't bots
// Returns an Array of ChatMember objects.
type GetChatAdministrators struct {
	ChatID any `json:"chat_id"`
}

func (entity *GetChatAdministrators) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetChatAdministrators) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity GetChatAdministrators) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 GetChatAdministrators
	return json.Marshal((x0)(entity))
}

func (GetChatAdministrators) MethodName() string {
	return "getChatAdministrators"
}

func (GetChatAdministrators) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result []types.ChatMember `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeArrayOfChatMember,
		Result: x1.Result,
	}
	return &result, nil
}
