// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// GetUserProfileAudios Use this method to get a list of profile audios for a user
// Returns a UserProfileAudios object.
type GetUserProfileAudios struct {
	Limit  int   `json:"limit,omitempty"`
	Offset int   `json:"offset,omitempty"`
	UserID int64 `json:"user_id"`
}

func (entity *GetUserProfileAudios) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetUserProfileAudios) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (GetUserProfileAudios) MethodName() string {
	return "getUserProfileAudios"
}

func (GetUserProfileAudios) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.UserProfileAudios `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeUserProfileAudios,
		Result: x1.Result,
	}
	return &result, nil
}
