// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// GetChatMemberCount Use this method to get the number of members in a chat
// Returns Int on success.
type GetChatMemberCount struct {
	ChatID any `json:"chat_id"`
}

func (entity *GetChatMemberCount) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetChatMemberCount) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity GetChatMemberCount) MarshalJSON() ([]byte, error) {
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 GetChatMemberCount
	return json.Marshal((x0)(entity))
}

func (GetChatMemberCount) MethodName() string {
	return "getChatMemberCount"
}

func (GetChatMemberCount) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result int `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeInteger,
		Result: x1.Result,
	}
	return &result, nil
}
