// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// GetAvailableGifts Returns the list of gifts that can be sent by the bot to users
// Requires no parameters
// Returns a Gifts object.
type GetAvailableGifts struct{}

func (entity *GetAvailableGifts) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetAvailableGifts) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (GetAvailableGifts) MethodName() string {
	return "getAvailableGifts"
}

func (GetAvailableGifts) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.Gifts `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeGifts,
		Result: x1.Result,
	}
	return &result, nil
}
