// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"gobotapi/types"
	rawTypes "gobotapi/types/raw"
)

// GetBusinessConnection Use this method to get information about the connection of the bot with a business account
// Returns a BusinessConnection object on success.
type GetBusinessConnection struct {
	BusinessConnectionID string `json:"business_connection_id"`
}

func (entity *GetBusinessConnection) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetBusinessConnection) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (GetBusinessConnection) MethodName() string {
	return "getBusinessConnection"
}

func (GetBusinessConnection) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.BusinessConnection `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBusinessConnection,
		Result: x1.Result,
	}
	return &result, nil
}
