// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// GetManagedBotAccessSettings Use this method to get the access settings of a managed bot
// Returns a BotAccessSettings object on success.
type GetManagedBotAccessSettings struct {
	UserID int64 `json:"user_id"`
}

func (entity *GetManagedBotAccessSettings) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetManagedBotAccessSettings) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (GetManagedBotAccessSettings) MethodName() string {
	return "getManagedBotAccessSettings"
}

func (GetManagedBotAccessSettings) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.BotAccessSettings `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBotAccessSettings,
		Result: x1.Result,
	}
	return &result, nil
}
