// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// GetUserPersonalChatMessages Use this method to get the last messages from the personal chat (i.e., the chat currently added to their profile) of a given user
// On success, an array of Message objects is returned.
type GetUserPersonalChatMessages struct {
	Limit  int   `json:"limit"`
	UserID int64 `json:"user_id"`
}

func (entity *GetUserPersonalChatMessages) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GetUserPersonalChatMessages) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (GetUserPersonalChatMessages) MethodName() string {
	return "getUserPersonalChatMessages"
}

func (GetUserPersonalChatMessages) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result []types.Message `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeArrayOfMessage,
		Result: x1.Result,
	}
	return &result, nil
}
