// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// GiftPremiumSubscription Gifts a Telegram Premium subscription to the given user
// Returns True on success.
type GiftPremiumSubscription struct {
	MonthCount    int                   `json:"month_count"`
	StarCount     int                   `json:"star_count"`
	Text          string                `json:"text,omitempty"`
	TextEntities  []types.MessageEntity `json:"text_entities,omitempty"`
	TextParseMode string                `json:"text_parse_mode,omitempty"`
	UserID        int64                 `json:"user_id"`
}

func (entity *GiftPremiumSubscription) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *GiftPremiumSubscription) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (GiftPremiumSubscription) MethodName() string {
	return "giftPremiumSubscription"
}

func (GiftPremiumSubscription) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
