// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"gobotapi/types"
	rawTypes "gobotapi/types/raw"
)

// HideGeneralForumTopic Use this method to hide the 'General' topic in a forum supergroup chat
// The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights
// The topic will be automatically closed if it was open
// Returns True on success.
type HideGeneralForumTopic struct {
	ChatID any `json:"chat_id"`
}

func (entity *HideGeneralForumTopic) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *HideGeneralForumTopic) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity HideGeneralForumTopic) MarshalJSON() ([]byte, error) {
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 HideGeneralForumTopic
	return json.Marshal((x0)(entity))
}

func (HideGeneralForumTopic) MethodName() string {
	return "hideGeneralForumTopic"
}

func (HideGeneralForumTopic) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
