// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// PostStory Posts a story on behalf of a managed business account
// Requires the can_manage_stories business bot right
// Returns Story on success.
type PostStory struct {
	ActivePeriod         int                     `json:"active_period"`
	Areas                []types.StoryArea       `json:"areas,omitempty"`
	BusinessConnectionID string                  `json:"business_connection_id"`
	Caption              string                  `json:"caption,omitempty"`
	CaptionEntities      []types.MessageEntity   `json:"caption_entities,omitempty"`
	Content              types.InputStoryContent `json:"content"`
	ParseMode            string                  `json:"parse_mode,omitempty"`
	PostToChatPage       bool                    `json:"post_to_chat_page,omitempty"`
	ProtectContent       bool                    `json:"protect_content,omitempty"`
}

func (entity *PostStory) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *PostStory) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (PostStory) MethodName() string {
	return "postStory"
}

func (PostStory) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.Story `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeStory,
		Result: x1.Result,
	}
	return &result, nil
}
