// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// RemoveMyProfilePhoto Removes the profile photo of the bot
// Requires no parameters
// Returns True on success.
type RemoveMyProfilePhoto struct{}

func (entity *RemoveMyProfilePhoto) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *RemoveMyProfilePhoto) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (RemoveMyProfilePhoto) MethodName() string {
	return "removeMyProfilePhoto"
}

func (RemoveMyProfilePhoto) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
