// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// ReplaceManagedBotToken Use this method to revoke the current token of a managed bot and generate a new one
// Returns the new token as String on success.
type ReplaceManagedBotToken struct {
	UserID int64 `json:"user_id"`
}

func (entity *ReplaceManagedBotToken) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *ReplaceManagedBotToken) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (ReplaceManagedBotToken) MethodName() string {
	return "replaceManagedBotToken"
}

func (ReplaceManagedBotToken) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result string `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeString,
		Result: x1.Result,
	}
	return &result, nil
}
