// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// RepostStory Reposts a story on behalf of a business account from another business account
// Both business accounts must be managed by the same bot, and the story on the source account must have been posted (or reposted) by the bot
// Requires the can_manage_stories business bot right for both business accounts
// Returns Story on success.
type RepostStory struct {
	ActivePeriod         int    `json:"active_period"`
	BusinessConnectionID string `json:"business_connection_id"`
	FromChatID           int64  `json:"from_chat_id"`
	FromStoryID          int64  `json:"from_story_id"`
	PostToChatPage       bool   `json:"post_to_chat_page,omitempty"`
	ProtectContent       bool   `json:"protect_content,omitempty"`
}

func (entity *RepostStory) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *RepostStory) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (RepostStory) MethodName() string {
	return "repostStory"
}

func (RepostStory) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.Story `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeStory,
		Result: x1.Result,
	}
	return &result, nil
}
