// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// SendMessageDraft Use this method to stream a partial message to a user while the message is being generated
// Note that the streamed draft is ephemeral and acts as a temporary 30-second preview - once the output is finalized, you must call sendMessage with the complete message to persist it in the user's chat
// Returns True on success.
type SendMessageDraft struct {
	ChatID          int64                 `json:"chat_id"`
	DraftID         int64                 `json:"draft_id"`
	Entities        []types.MessageEntity `json:"entities,omitempty"`
	MessageThreadID int64                 `json:"message_thread_id,omitempty"`
	ParseMode       string                `json:"parse_mode,omitempty"`
	Text            string                `json:"text,omitempty"`
}

func (entity *SendMessageDraft) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *SendMessageDraft) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (SendMessageDraft) MethodName() string {
	return "sendMessageDraft"
}

func (SendMessageDraft) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
