// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// SendContact Use this method to send phone contacts
// On success, the sent Message is returned.
type SendContact struct {
	AllowPaidBroadcast   bool                   `json:"allow_paid_broadcast,omitempty"`
	BusinessConnectionID string                 `json:"business_connection_id,omitempty"`
	ChatID               any                    `json:"chat_id"`
	DisableNotification  bool                   `json:"disable_notification,omitempty"`
	FirstName            string                 `json:"first_name"`
	LastName             string                 `json:"last_name,omitempty"`
	MessageEffectID      string                 `json:"message_effect_id,omitempty"`
	MessageThreadID      int64                  `json:"message_thread_id,omitempty"`
	PhoneNumber          string                 `json:"phone_number"`
	ProtectContent       bool                   `json:"protect_content,omitempty"`
	ReplyMarkup          any                    `json:"reply_markup,omitempty"`
	ReplyParameters      *types.ReplyParameters `json:"reply_parameters,omitempty"`
	Vcard                string                 `json:"vcard,omitempty"`
}

func (entity *SendContact) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *SendContact) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity SendContact) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if nilCheck(entity.ReplyParameters) {
		entity.ReplyParameters = nil
	}
	if nilCheck(entity.ReplyMarkup) {
		entity.ReplyMarkup = nil
	}
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	if entity.ReplyMarkup != nil {
		switch entity.ReplyMarkup.(type) {
		case *types.InlineKeyboardMarkup, *types.ReplyKeyboardMarkup, *types.ReplyKeyboardRemove, *types.ForceReply:
			break
		default:
			return nil, fmt.Errorf("reply_markup: unknown type: %T", entity.ReplyMarkup)
		}
	}
	type x0 SendContact
	return json.Marshal((x0)(entity))
}

func (SendContact) MethodName() string {
	return "sendContact"
}

func (SendContact) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.Message `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeMessage,
		Result: x1.Result,
	}
	return &result, nil
}
