// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/Squirrel-Network/gobotapi/types"
	rawTypes "github.com/Squirrel-Network/gobotapi/types/raw"
)

// SendVoice Use this method to send audio files, if you want Telegram clients to display the file as a playable voice message
// For this to work, your audio must be in an .OGG file encoded with OPUS (other formats may be sent as Audio or Document)
// On success, the sent Message is returned
// Bots can currently send voice messages of up to 50 MB in size, this limit may be changed in the future.
type SendVoice struct {
	AllowSendingWithoutReply bool                  `json:"allow_sending_without_reply,omitempty"`
	Caption                  string                `json:"caption,omitempty"`
	CaptionEntities          []types.MessageEntity `json:"caption_entities,omitempty"`
	ChatID                   int64                 `json:"chat_id"`
	DisableNotification      bool                  `json:"disable_notification,omitempty"`
	Duration                 int                   `json:"duration,omitempty"`
	ParseMode                string                `json:"parse_mode,omitempty"`
	ProtectContent           bool                  `json:"protect_content,omitempty"`
	ReplyMarkup              interface{}           `json:"reply_markup,omitempty"`
	ReplyToMessageID         int64                 `json:"reply_to_message_id,omitempty"`
	Voice                    rawTypes.InputFile    `json:"voice,omitempty"`
}

func (entity *SendVoice) Files() map[string]rawTypes.InputFile {
	files := make(map[string]rawTypes.InputFile)
	switch entity.Voice.(type) {
	case types.InputFile:
		files["voice"] = entity.Voice
		entity.Voice = nil
	}
	return files
}

func (entity SendVoice) MarshalJSON() ([]byte, error) {
	if entity.ReplyMarkup != nil {
		switch entity.ReplyMarkup.(type) {
		case *types.InlineKeyboardMarkup, *types.ReplyKeyboardMarkup, *types.ReplyKeyboardRemove, *types.ForceReply:
			break
		default:
			return nil, fmt.Errorf("reply_markup: unknown type: %T", entity.ReplyMarkup)
		}
	}
	type x0 SendVoice
	return json.Marshal((x0)(entity))
}

func (SendVoice) MethodName() string {
	return "sendVoice"
}

func (SendVoice) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.Message `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeMessage,
		Result: x1.Result,
	}
	return &result, nil
}
