// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// SetBusinessAccountBio Changes the bio of a managed business account
// Requires the can_change_bio business bot right
// Returns True on success.
type SetBusinessAccountBio struct {
	Bio                  string `json:"bio,omitempty"`
	BusinessConnectionID string `json:"business_connection_id"`
}

func (entity *SetBusinessAccountBio) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *SetBusinessAccountBio) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (SetBusinessAccountBio) MethodName() string {
	return "setBusinessAccountBio"
}

func (SetBusinessAccountBio) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
