// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// SetBusinessAccountUsername Changes the username of a managed business account
// Requires the can_change_username business bot right
// Returns True on success.
type SetBusinessAccountUsername struct {
	BusinessConnectionID string `json:"business_connection_id"`
	Username             string `json:"username,omitempty"`
}

func (entity *SetBusinessAccountUsername) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *SetBusinessAccountUsername) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (SetBusinessAccountUsername) MethodName() string {
	return "setBusinessAccountUsername"
}

func (SetBusinessAccountUsername) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
