// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// SetMyProfilePhoto Changes the profile photo of the bot
// Returns True on success.
type SetMyProfilePhoto struct {
	Photo types.InputProfilePhoto `json:"photo"`
}

func (entity *SetMyProfilePhoto) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *SetMyProfilePhoto) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (SetMyProfilePhoto) MethodName() string {
	return "setMyProfilePhoto"
}

func (SetMyProfilePhoto) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
