// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"gobotapi/types"
	rawTypes "gobotapi/types/raw"
)

// SetMyDescription Use this method to change the bot's description, which is shown in the chat with the bot if the chat is empty
// Returns True on success.
type SetMyDescription struct {
	Description  string `json:"description,omitempty"`
	LanguageCode string `json:"language_code,omitempty"`
}

func (entity *SetMyDescription) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *SetMyDescription) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (SetMyDescription) MethodName() string {
	return "setMyDescription"
}

func (SetMyDescription) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
