// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/Squirrel-Network/gobotapi/types"
	rawTypes "github.com/Squirrel-Network/gobotapi/types/raw"
)

// SetChatAdministratorCustomTitle Use this method to set a custom title for an administrator in a supergroup promoted by the bot
// Returns True on success.
type SetChatAdministratorCustomTitle struct {
	ChatID      int64  `json:"chat_id"`
	CustomTitle string `json:"custom_title"`
	UserID      int64  `json:"user_id"`
}

func (entity *SetChatAdministratorCustomTitle) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (SetChatAdministratorCustomTitle) MethodName() string {
	return "setChatAdministratorCustomTitle"
}

func (SetChatAdministratorCustomTitle) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
