// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// SetBusinessAccountProfilePhoto Changes the profile photo of a managed business account
// Requires the can_edit_profile_photo business bot right
// Returns True on success.
type SetBusinessAccountProfilePhoto struct {
	BusinessConnectionID string                  `json:"business_connection_id"`
	IsPublic             bool                    `json:"is_public,omitempty"`
	Photo                types.InputProfilePhoto `json:"photo"`
}

func (entity *SetBusinessAccountProfilePhoto) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *SetBusinessAccountProfilePhoto) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (SetBusinessAccountProfilePhoto) MethodName() string {
	return "setBusinessAccountProfilePhoto"
}

func (SetBusinessAccountProfilePhoto) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
