// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"gobotapi/types"
	rawTypes "gobotapi/types/raw"
)

// SetStickerSetThumbnail Use this method to set the thumbnail of a regular or mask sticker set
// The format of the thumbnail file must match the format of the stickers in the set
// Returns True on success.
type SetStickerSetThumbnail struct {
	Name      string                    `json:"name"`
	Thumbnail rawTypes.InputFile        `json:"thumbnail,omitempty"`
	UserID    int64                     `json:"user_id"`
	Progress  rawTypes.ProgressCallable `json:"-"`
}

func (entity *SetStickerSetThumbnail) ProgressCallable() rawTypes.ProgressCallable {
	return entity.Progress
}

func (entity *SetStickerSetThumbnail) Files() map[string]rawTypes.InputFile {
	files := make(map[string]rawTypes.InputFile)
	switch entity.Thumbnail.(type) {
	case types.InputBytes:
		files["thumbnail"] = entity.Thumbnail
		entity.Thumbnail = types.InputURL("attach://thumbnail")
	}
	return files
}

func (SetStickerSetThumbnail) MethodName() string {
	return "setStickerSetThumbnail"
}

func (SetStickerSetThumbnail) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
