// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"fmt"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
	"reflect"
)

// SetChatMemberTag Use this method to set a tag for a regular member in a group or a supergroup
// The bot must be an administrator in the chat for this to work and must have the can_manage_tags administrator right
// Returns True on success.
type SetChatMemberTag struct {
	ChatID any    `json:"chat_id"`
	Tag    string `json:"tag,omitempty"`
	UserID int64  `json:"user_id"`
}

func (entity *SetChatMemberTag) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *SetChatMemberTag) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (entity SetChatMemberTag) MarshalJSON() ([]byte, error) {
	nilCheck := func(val any) bool {
		if val == nil {
			return true
		}
		v := reflect.ValueOf(val)
		k := v.Kind()
		switch k {
		case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.UnsafePointer, reflect.Interface, reflect.Slice:
			return v.IsNil()
		default:
			return false
		}
	}
	_ = nilCheck
	if entity.ChatID != nil {
		switch entity.ChatID.(type) {
		case int, int64, string:
			break
		default:
			return nil, fmt.Errorf("chat_id: unknown type: %T", entity.ChatID)
		}
	}
	type x0 SetChatMemberTag
	return json.Marshal((x0)(entity))
}

func (SetChatMemberTag) MethodName() string {
	return "setChatMemberTag"
}

func (SetChatMemberTag) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
