// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/Squirrel-Network/gobotapi/types"
	rawTypes "github.com/Squirrel-Network/gobotapi/types/raw"
)

// StopPoll Use this method to stop a poll which was sent by the bot
// On success, the stopped Poll is returned.
type StopPoll struct {
	ChatID      int64                       `json:"chat_id"`
	MessageID   int64                       `json:"message_id"`
	ReplyMarkup *types.InlineKeyboardMarkup `json:"reply_markup,omitempty"`
}

func (entity *StopPoll) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *StopPoll) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (StopPoll) MethodName() string {
	return "stopPoll"
}

func (StopPoll) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result types.Poll `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypePoll,
		Result: x1.Result,
	}
	return &result, nil
}
