// Code AutoGenerated; DO NOT EDIT.

package methods

import (
	"encoding/json"
	"github.com/GoBotApiOfficial/gobotapi/types"
	rawTypes "github.com/GoBotApiOfficial/gobotapi/types/raw"
)

// UpgradeGift Upgrades a given regular gift to a unique gift
// Requires the can_transfer_and_upgrade_gifts business bot right
// Additionally requires the can_transfer_stars business bot right if the upgrade is paid
// Returns True on success.
type UpgradeGift struct {
	BusinessConnectionID string `json:"business_connection_id"`
	KeepOriginalDetails  bool   `json:"keep_original_details,omitempty"`
	OwnedGiftID          string `json:"owned_gift_id"`
	StarCount            int    `json:"star_count,omitempty"`
}

func (entity *UpgradeGift) ProgressCallable() rawTypes.ProgressCallable {
	return nil
}

func (entity *UpgradeGift) Files() map[string]rawTypes.InputFile {
	return map[string]rawTypes.InputFile{}
}

func (UpgradeGift) MethodName() string {
	return "upgradeGift"
}

func (UpgradeGift) ParseResult(response []byte) (*rawTypes.Result, error) {
	var x1 struct {
		Result bool `json:"result"`
	}
	err := json.Unmarshal(response, &x1)
	if err != nil {
		return nil, err
	}
	result := rawTypes.Result{
		Kind:   types.TypeBoolean,
		Result: x1.Result,
	}
	return &result, nil
}
