// Code AutoGenerated; DO NOT EDIT.

package filters

import "github.com/Squirrel-Network/gobotapi/types"

type Filterable interface {
	types.CallbackQuery |
		types.ChatJoinRequest |
		types.ChatMemberUpdated |
		types.ChosenInlineResult |
		types.InlineQuery |
		types.Message |
		types.PreCheckoutQuery |
		types.ShippingQuery
}
