// Code AutoGenerated; DO NOT EDIT.

package filters

import "gobotapi/types"

type Filterable interface {
	types.CallbackQuery |
		types.ChatBoostRemoved |
		types.ChatBoostUpdated |
		types.ChatJoinRequest |
		types.ChatMemberUpdated |
		types.ChosenInlineResult |
		types.InlineQuery |
		types.Message |
		types.MessageReactionCountUpdated |
		types.MessageReactionUpdated |
		types.PreCheckoutQuery |
		types.ShippingQuery
}
