// Code AutoGenerated; DO NOT EDIT.

package filters

import "github.com/GoBotApiOfficial/gobotapi/types"

type Filterable interface {
	types.BusinessConnection |
		types.BusinessMessagesDeleted |
		types.CallbackQuery |
		types.ChatBoostRemoved |
		types.ChatBoostUpdated |
		types.ChatJoinRequest |
		types.ChatMemberUpdated |
		types.ChosenInlineResult |
		types.InlineQuery |
		types.Message |
		types.MessageReactionCountUpdated |
		types.MessageReactionUpdated |
		types.PaidMediaPurchased |
		types.PreCheckoutQuery |
		types.ShippingQuery
}
